// Central typed integration copy. Task32 owns the complete locale catalog and styling.
import type { OpenEnaModelTabsV3Copy } from "./OpenEnaModelTabsV3";
import type { OpenEnaUnitsPanelV3Copy } from "./OpenEnaUnitsPanelV3";
import type { OpenEnaHorizonsPanelV3Copy } from "./OpenEnaHorizonsPanelV3";
import type { OpenEnaWindowsPanelV3Copy } from "./OpenEnaWindowsPanelV3";
import type { OpenEnaCodesPanelV3Copy } from "./OpenEnaCodesPanelV3";
import type { OpenEnaOrderPolicyEditorV3Copy } from "./OpenEnaOrderPolicyEditorV3";

export const tabsCopy: OpenEnaModelTabsV3Copy = {
  tabListLabel: "Model configuration",
  tabs: { units: "Units", horizons: "Horizons", windows: "Windows", codes: "Codes" },
  tabDiagnosticLabel: ({ label, errors, warnings }) => `${label}, ${errors} error and ${warnings} warning`,
  help: {
    units: { buttonLabel: "About Units settings", heading: "Units help", description: "Choose Unit fields." },
    horizons: { buttonLabel: "About Horizons settings", heading: "Horizons help", description: "Choose Horizon fields." },
    windows: { buttonLabel: "About Windows settings", heading: "Windows help", description: "Choose a Window." },
    codes: { buttonLabel: "About Codes settings", heading: "Codes help", description: "Choose Code fields." },
  },
  status: {
    label: "Model status",
    configuration: { incomplete: "Configuration incomplete", ready: "Configuration ready" },
    result: {
      none: "No result",
      running: "Running",
      current: "Current result",
      stale: "Stale result",
      error: "Run error",
      obsolete: "Obsolete run",
      cancelled: "Cancelled run",
    },
    summary: ({ configuration, result }) => `${configuration}. ${result}.`,
  },
  scientificSummary: {
    label: "Scientific configuration",
    fieldLabels: {
      family: "Family",
      model: "Model",
      window: "Window",
      weighting: "Weighting",
      rotation: "Rotation",
      units: "Units count",
      horizons: "Horizons count",
      groups: "Groups count",
      codes: "Codes count",
    },
    family: { standard: "Standard ENA", ona: "Ordered Network Analysis" },
    model: { EndPoint: "End Point", SeparateTrajectory: "Separate Trajectory", AccumulatedTrajectory: "Accumulated Trajectory" },
    window: { MovingStanzaWindow: "Moving Stanza", Conversation: "Conversation" },
    weighting: { binary: "Binary", frequency: "Frequency", "frequency-sum": "Frequency (sum)" },
    rotation: { svd: "SVD", means: "Means", reference: "Reference" },
    count: (value) => `${value}`,
    unavailable: "Unavailable",
  },
  diagnostics: {
    label: "Model diagnostics",
    globalLabel: "Global diagnostics",
    scopeLabels: {
      dataset: "Dataset",
      units: "Units",
      horizons: "Horizons",
      windows: "Windows",
      codes: "Codes",
      rotation: "Rotation",
      reference: "Reference",
      resources: "Resources",
      migration: "Migration",
      model: "Model",
    },
    severityLabels: { error: "Error", warning: "Warning", information: "Information" },
    localize: (diagnostic) => ({ summary: `Review ${diagnostic.fieldPath ?? diagnostic.scope}`, detail: diagnostic.id }),
    evidenceLabel: "Evidence",
    evidenceTotal: (totalCount) => `${totalCount} affected rows`,
    evidenceSample: (_sample, index) => `Evidence sample ${index + 1}`,
    evidenceTruncated: "More evidence is available",
    suggestedAction: (action) => ({ label: `Apply ${action.id}`, confirmation: `Confirm ${action.id}` }),
    confirmationTitle: "Confirm scientific change",
    confirmLabel: "Confirm",
    cancelLabel: "Cancel",
  },
};

export const unitsCopy: OpenEnaUnitsPanelV3Copy = {
  units: "Unit fields",
  unitPickerEmpty: "Add a Unit field",
  addRemoveFields: (label) => `Add or remove ${label} fields`,
  removeField: (field, label) => `Remove ${field} from ${label}`,
  counts: "Units and Groups",
  unitCount: (count) => `${count} Units`,
  groupCount: (count) => `${count} Groups`,
  unavailable: "Unavailable for this draft",
  groupStability: "Group stability",
  stableGroup: "Stable within every Unit",
  unstableGroup: "Group changes within at least one Unit",
  group: "Create Sample / Group",
  noGroup: "No Group",
  unavailableGroupField: (field) => `${field} (unavailable current field)`,
  means: "Means contrast",
  negativeLevel: "Negative level",
  positiveLevel: "Positive level",
  noMeansLevel: "No level selected",
  unavailableMeansLevel: (label) => `${label} (unavailable current level)`,
  meansDirection: (negative, positive) => `${negative} to ${positive}`,
  meansUnavailable: "Choose a current, stable Group to select Means levels.",
  meansInvalid: "Means remains selected and needs a Group and two distinct levels.",
  groupToolbar: "Group actions",
  collapseGroups: "Collapse all group option panels",
  openGroupOptions: "Open all group display options",
  groupOptionsUnavailable: "A result with Groups is required.",
  hideGroups: "Hide all group layers",
  restoreGroups: "Restore all group layers",
  excludeGroup: "Exclude group configuration",
  hideUnavailable: "A result for this dataset and family is required.",
  excludeUnavailable: "Choose a Group before excluding it.",
  undoGroupExclusion: "Undo Group exclusion",
  groupExcluded: "Group configuration excluded. The retained result is stale.",
  currentDraftGroups: "Current draft Groups",
  retainedPlotGroups: "Groups from the retained result",
  stalePlotGroups: "These display controls belong to the retained stale result.",
  noPlotGroups: "No result-bound Group display is available.",
  diagnosticLabel: "Group stability diagnostics",
};

export const horizonsCopy: OpenEnaHorizonsPanelV3Copy = {
  horizonIdentity: "Horizon identity",
  horizonPickerEmpty: "Add a Horizon field",
  addRemoveFields: (label) => `Add or remove ${label} fields`,
  removeField: (field, label) => `Remove ${field} from ${label}`,
  counts: "Horizon structure counts",
  unitCount: (count) => `${count} Units`,
  horizonCount: (count) => `${count} Horizons`,
  observationCount: (count) => `${count} Unit by Horizon observations`,
  unavailable: "Unavailable for this draft",
  structure: "Unit by Horizon structure",
  structureColumns: { unit: "Unit", horizon: "Horizon", rows: "Source rows" },
  sharedHorizons: (count) => `${count} shared Horizons`,
  noSharedHorizons: "No shared Horizons",
  singleRowObservations: (count) => `${count} single-row observations`,
  extremeObservations: (minimum, maximum) => `Observed rows range from ${minimum} to ${maximum}`,
  boundedRows: (shown, total) => `Showing ${shown} of ${total} observations`,
  trajectoryOrder: "Trajectory step order",
  horizonOrderNotApplicable: "Horizon order is not applicable to End Point; the inactive draft is preserved.",
  onaOrderNotApplicable: "Horizon order is not applicable to ONA End Point.",
  sequences: "Per-Unit sequence preview",
  sequence: (unit, steps) => `${unit}: ${steps}`,
  sequenceUnavailable: "Sequence preview unavailable for this context",
  boundedSequences: (shown, total) => `Showing ${shown} of ${total} Unit sequences`,
  tieAction: "Add tie-breaker order key",
  diagnostics: "Horizon diagnostics",
};

export const windowsCopy: OpenEnaWindowsPanelV3Copy = {
  model: "Model",
  models: {
    EndPoint: "EndPoint",
    SeparateTrajectory: "Separate Trajectory",
    AccumulatedTrajectory: "Accumulated Trajectory",
  },
  window: "Window",
  movingStanza: "Moving Stanza Window",
  conversation: "Conversation / Horizon Window",
  conversationExplanation: "All source rows in the same typed Horizon contribute; extent and row order are inactive.",
  backward: "Backward context",
  forward: "Forward context",
  finite: "Finite",
  entireHorizon: "Entire Horizon",
  finiteValue: "Rows",
  backwardCurrentOnly: "Includes the current row only within its Horizon.",
  backwardFinite: (preceding) => `Includes the current row and at most ${preceding} preceding rows within its Horizon.`,
  backwardInfinite: "Includes the current row and every preceding row within its Horizon.",
  forwardNone: "Adds no following rows.",
  forwardFinite: (following) => `Adds at most ${following} following rows within its Horizon; the current row is excluded from this count.`,
  forwardInfinite: "Adds every following row within its Horizon; the current row is excluded from this count.",
  extentErrors: {
    required: "Enter an extent.",
    integer: "Use a whole decimal integer or Infinity.",
    minimumBackward: "Backward context must be at least 1.",
    minimumForward: "Forward context must be at least 0.",
    safeInteger: "The extent exceeds the largest safe integer.",
  },
  rowOrder: "Row order",
  weighting: "Weighting",
  binary: "Binary",
  binaryHelp: "Binary accepts one consistent 0/1 numeric or false/true Boolean representation per Code.",
  frequency: "Frequency",
  frequencyHelp: "Frequency accepts finite nonnegative numeric Code values, including decimals.",
  rotation: "Projection & Rotation",
  svd: "SVD",
  means: "Means",
  reference: "Reference",
  centerAlign: "Align target-fitted center to the origin",
  meansInUnits: "Set the ordered Means contrast in Units.",
  goToMeans: "Open Means contrast in Units",
  meansTrajectoryInvalid: "Direct Means rotation requires EndPoint. The Means selection is preserved.",
  chooseSvd: "Choose SVD",
  chooseReference: "Choose Reference",
  returnToEndpoint: "Return to EndPoint",
  referenceSelection: "Reference source",
  noReference: "No Reference selected",
  unavailableReference: (name) => `${name} (unavailable current Reference)`,
  referenceRequired: "Choose an owned validated Reference. The Reference selection remains active and Run is blocked.",
  referencePreviewUnavailable: "Current owned Reference evidence is unavailable for this exact context.",
  referenceIncompatible: "The selected Reference is incompatible with this target. The selection is preserved.",
  referenceCompatible: "Compatible with the current target configuration.",
  referenceFacts: "Reference evidence",
  referenceName: "Source",
  referenceHash: "Content hash",
  sourceFit: "Source fit",
  sourceFitMethods: { svd: "Source SVD", means: "Source Means" },
  sourcePopulation: "Source population",
  sourcePopulations: { "endpoint-units": "Endpoint Units" },
  sourceObservations: "Source observations",
  basis: "Fixed basis",
  basisSummary: (codes, edges, axes) => `${codes} Codes, ${edges} edges, ${axes} axes`,
  fixedCentering: "Centering is fixed by the source Reference",
  centeredAtOrigin: "source fit aligned to origin",
  centeredAtSourceMean: "source fit center retained",
  targetProjection: "Target projection",
  targetProjectionPending: "No current target projection has been adopted.",
  targetProjectionSummary: (rank, variance) => `Target rank ${rank}; fixed-axis variance ${variance}`,
  compatibilityReasons: "Compatibility details",
  referenceCompatibilityReason: (reason) => `Reference compatibility: ${reason.replaceAll("-", " ")}`,
  resources: "Execution resource preflight",
  resourcesUnavailable: "No current compiler-owned preflight is available for this exact scientific context.",
  resourcesInvalidRaw: "Active raw Window input is invalid, so there is no executable plan or current estimate.",
  resourcesInvalidDraft: "The active draft is invalid, so there is no executable plan or current estimate.",
  resourceStatus: "Current preflight admitted",
  resourceRows: (value) => `${value} rows`,
  resourceDimensions: (value) => `${value} adjacency dimensions`,
  resourceVisits: (value) => `${value} estimated window visits`,
  resourcePeak: (value) => `${value} estimated peak bytes`,
  resourceRotation: (value) => `${value} estimated rotation work units`,
  resourceNoTruncation: "Hard caps block execution; they never authorize truncating rows, Codes, windows, or data.",
  onaContract: "Ordered Network Analysis Window contract",
  onaForwardFixed: "Forward context is fixed at 0 for Ordered Network Analysis.",
  onaWeightingFixed: "Frequency weighting is fixed for Ordered Network Analysis.",
  onaModelFixed: "EndPoint is fixed for Ordered Network Analysis.",
  onaRotationFixed: "SVD is fixed for Ordered Network Analysis.",
};

export const codesCopy: OpenEnaCodesPanelV3Copy = {
  intro: "Selected codes become the nodes in the model network.",
  family: {
    legend: "Analysis family",
    methodBoundaryLabel: "Method boundary",
    selectedLabel: "Selected",
    ena: {
      label: "Standard ENA",
      description: "Undirected co-occurrence",
      methodBoundary: "Standard boundary",
    },
    ona: {
      label: "Ordered Network Analysis",
      description: "Directed ground-response",
      methodBoundary: "ONA boundary",
    },
  },
  familyChanged: (family) =>
    `Analysis family changed to ${family}. Independent settings restored.`,
  toolbar: "Code actions",
  hideCodes: "Hide all code nodes",
  restoreCodes: "Restore all code nodes",
  excludeAllCodes: "Exclude all selected Codes",
  hideUnavailable: "Select at least one Code before hiding nodes.",
  excludeUnavailable: "There are no selected Codes to exclude.",
  selectedCodes: "Selected Codes",
  codeType: "Type",
  positiveCountLabel: "Positive rows",
  profileTypes: {
    "binary-number": "Numeric Binary",
    "binary-boolean": "Boolean Binary",
    frequency: "Frequency",
  },
  positiveCount: (count) => `${count} positive rows`,
  unavailable: "Unavailable for this exact draft",
  diagnostics: "Diagnostics",
  diagnosticsUnavailable:
    "Compiler diagnostics are unavailable for this exact draft.",
  chooseColor: (code) => `Choose color for ${code}`,
  hideCode: (code) => `Hide ${code} node`,
  showCode: (code) => `Show ${code} node`,
  excludeCode: (code) => `Exclude ${code} Code`,
  reorderCode: (code) => `Reorder ${code}`,
  reorderInstructions:
    "Press Alt+Arrow Up or Alt+Arrow Down to change display order.",
  moveUnavailable:
    "Display reorder is unavailable until selected Codes are distinct.",
  displayActionUnavailable:
    "Display actions are unavailable until selected Codes are distinct.",
  restoreBeforeCodeVisibility:
    "Restore all Codes before changing one Code visibility.",
  manageCodes: "Manage Codes",
  closeManager: "Close Code manager",
  managerTitle: "Manage Codes",
  managerInstructions:
    "Compatible source fields can be selected. Incompatible fields remain visible with reasons.",
  addCode: (code) => `Select ${code} as a Code`,
  incompatibilityReason: {
    missing: "Missing from the current dataset",
    "active-role": "Used by an active scientific role",
    "binary-values":
      "Values do not use one uniform numeric 0/1 or Boolean representation",
    "frequency-values": "Values are not all finite nonnegative numbers",
    "duplicate-selection":
      "Selected more than once; remove it to repair the draft",
  },
  noCodesTitle: "No codes selected",
  minimumThreeCodes:
    "At least three distinct Codes are required to run a model.",
  otherSettingsPreserved:
    "Units, Horizons, Windows, Order, Rotation, and the other analysis family remain preserved.",
  undo: "Undo Code exclusion",
};

export const orderCopy: OpenEnaOrderPolicyEditorV3Copy = {
  sortByFields: "Sort by fields",
  useSourceOrder: "Use source order",
  addKey: "Add order key",
  removeKey: (index) => `Remove order key ${index + 1}`,
  moveKeyUp: (index) => `Move order key ${index + 1} up`,
  moveKeyDown: (index) => `Move order key ${index + 1} down`,
  keyLabel: (index) => `Order key ${index + 1}`,
  field: "Field",
  missingField: (field) => `${field} (unavailable current field)`,
  chooseField: "Choose a field",
  direction: "Direction",
  ascending: "Ascending",
  descending: "Descending",
  comparator: "Comparator",
  comparators: {
    number: "Number",
    date: "Date (YYYY-MM-DD)",
    datetime: "Datetime (ISO-8601, offset in value)",
    "ordered-category": "Ordered category",
    text: "Text",
  },
  categoryLevels: "Ordered category levels",
  addCategoryLevel: "Add category level",
  removeCategoryLevel: (index) => `Remove category level ${index + 1}`,
  moveCategoryLevelUp: (index) => `Move category level ${index + 1} up`,
  moveCategoryLevelDown: (index) => `Move category level ${index + 1} down`,
  scalarType: "Value type",
  scalarTypes: { string: "String", number: "Number", boolean: "Boolean" },
  scalarValue: "Value",
  booleanValues: { true: "true", false: "false" },
  textLocale: "Locale",
  textSensitivity: "Sensitivity",
  textSensitivities: { base: "Base", accent: "Accent", case: "Case", variant: "Variant" },
  textNumeric: "Numeric collation",
  invalidEditor: "Complete every active order field before running.",
  sourceStatement: "I confirm the observed source sequence for this exact dataset and field context.",
  reviewSourceStatement: "Review source-order statement",
  acceptSourceStatement: "Accept statement",
  cancelSourceStatement: "Cancel",
  sourceConfirmed: "Source order explicitly confirmed",
  sourceUnconfirmed: "Source order is not confirmed",
  sourceBindingChanged: "The dataset or scientific context changed. Review the statement again.",
  datasetHash: "Dataset",
  rowCount: "Rows",
  relevantFields: "Relevant fields",
  confirmationVersion: "Confirmation version",
  confirmedAt: "Confirmed at",
  unavailable: "Unavailable for this context",
};
