import type {
  AcademyLesson,
  AcademyLevel,
  AcademyTrack,
  AcademyVisual,
} from "./academy-types";

interface BackfillLessonSpec {
  sequence: number;
  slug: string;
  title: string;
  track: AcademyTrack;
  level: AcademyLevel;
  visual: AcademyVisual;
  publishedAt: string;
  tags: string[];
  focus: string;
  practicalDecision: string;
  sensitivity: string;
  evidenceReturn: string;
  boundary: string;
  pairedSourceLabel: string;
  pairedSourceUrl: string;
}

const sharedDownloads = [
  {
    label: "Synthetic design-talk dataset",
    href: "/data/academy/ena-design-talk-sample.csv",
    note: "A fictional 48-row CSV for learning the workflow, not for substantive inference.",
  },
  {
    label: "Codebook and coding examples",
    href: "/data/academy/ena-design-talk-codebook.csv",
    note: "Definitions, inclusion rules, exclusion rules, and one positive example for each code.",
  },
  {
    label: "Blank ENA decision record",
    href: "/data/academy/ena-analysis-decision-record.md",
    note: "A reusable worksheet for recording the question, units, conversations, codes, window, and claim boundary.",
  },
] as const;

const tutorialSource = {
  label: "Shaffer, Collier, and Ruis: A Tutorial on Epistemic Network Analysis",
  url: "https://doi.org/10.18608/jla.2016.33.3",
} as const;

const backfillLessonSpecs: BackfillLessonSpec[] = [
  {
    sequence: 6,
    slug: "audit-coding-reliability-and-consensus",
    title: "Audit Coding Reliability and Consensus Before ENA",
    track: "data-preparation",
    level: "intermediate",
    visual: "prepare",
    publishedAt: "2026-07-23",
    tags: ["coding reliability", "consensus coding", "codebook revision", "adjudication", "academy step 6"],
    focus: "testing whether the codebook is applied consistently enough for connections among codes to have a stable interpretation",
    practicalDecision: "select a representative double-coded subset, calculate agreement at the same segment and code level used by the model, inspect disagreements, revise definitions, and record adjudication without hiding the pre-consensus results",
    sensitivity: "compare unit networks built from coder A, coder B, and the adjudicated matrix for the double-coded subset, paying special attention to edges involving rare or frequently confused codes",
    evidenceReturn: "link every resolved disagreement to the original utterance, both coder judgments, the rule invoked, and the final rationale",
    boundary: "Agreement coefficients do not prove construct validity, and consensus does not erase ambiguity. A high value can coexist with a narrow codebook, prevalent negative cases, or shared coder bias.",
    pairedSourceLabel: "Journal of Learning Analytics record for the foundational ENA tutorial",
    pairedSourceUrl: "https://learning-analytics.info/index.php/JLA/article/view/4329",
  },
  {
    sequence: 7,
    slug: "justify-a-moving-stanza-window",
    title: "Justify a Moving Stanza Window From Interaction Context",
    track: "research-design",
    level: "intermediate",
    visual: "frame",
    publishedAt: "2026-07-24",
    tags: ["moving stanza window", "context length", "conversation boundary", "temporal proximity", "academy step 7"],
    focus: "choosing how many nearby rows may contribute to a modeled connection and why that span represents meaningful context in the activity",
    practicalDecision: "define conversation boundaries first, justify a candidate window from turn-taking and task structure, state whether the current row connects backward or symmetrically, and freeze the rule before comparing groups",
    sensitivity: "rerun at least two nearby defensible window sizes while holding codes, units, conversations, normalization, and rotation constant, then compare edge ranks and substantive conclusions",
    evidenceReturn: "inspect row sequences around edges that change most and determine whether the added proximity reflects a real conversational relation or only mechanical adjacency",
    boundary: "No window is universally correct. A stable picture across arbitrary settings is not a substitute for theory, and a window must never leak across unrelated conversations merely to increase edge density.",
    pairedSourceLabel: "Scoping the Emerging Field of Quantitative Ethnography",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_1",
  },
  {
    sequence: 8,
    slug: "separate-code-prevalence-from-connections",
    title: "Separate Code Prevalence From ENA Connections",
    track: "interpretation",
    level: "beginner",
    visual: "interpret",
    publishedAt: "2026-07-25",
    tags: ["code prevalence", "connection weight", "frequency audit", "relational interpretation", "academy step 8"],
    focus: "distinguishing how often a code occurs from how strongly it connects with other codes under the selected window",
    practicalDecision: "build a code-frequency table beside the edge table, identify codes that are common but weakly connected and rare but locally connected, and write separate descriptions for prevalence and relation",
    sensitivity: "compare edge patterns before and after reviewing one high-prevalence code, without deleting it simply because it dominates counts or keeping it simply because it is frequent",
    evidenceReturn: "trace a thick edge and a frequent isolated code to their source rows so readers can see why occurrence and co-occurrence answer different questions",
    boundary: "ENA does not make frequencies irrelevant. Rare, ubiquitous, or unevenly coded elements can shape a network, and normalized connections cannot be interpreted responsibly without the accompanying code distribution.",
    pairedSourceLabel: "Temporal collaboration in physical learning spaces",
    pairedSourceUrl: "https://doi.org/10.3390/s21092898",
  },
  {
    sequence: 9,
    slug: "model-nested-units-and-metadata",
    title: "Model Nested Units and Metadata Without Pseudoreplication",
    track: "research-design",
    level: "intermediate",
    visual: "frame",
    publishedAt: "2026-07-26",
    tags: ["nested units", "metadata hierarchy", "pseudoreplication", "group context", "academy step 9"],
    focus: "aligning the network unit with hierarchical data such as turns within students, students within teams, and teams within classrooms",
    practicalDecision: "draw the hierarchy, name the level represented by one network, retain parent identifiers as metadata, and choose an inferential comparison whose independent sampling level matches the design",
    sensitivity: "compare a defensible team-level model with a participant-contribution model only after stating how shared conversation context is allocated and how repeated observations are handled",
    evidenceReturn: "select one plotted unit and reconstruct every contributing row, conversation, participant, team, and class identifier to verify the intended nesting",
    boundary: "Creating many network rows does not create independent cases. ENA can model contextual contributions, but conventional tests still require dependence assumptions that reflect clustering and repeated measurement.",
    pairedSourceLabel: "Topic Modeling for Code Discovery in Large Scale Text Data",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_2",
  },
  {
    sequence: 10,
    slug: "inspect-unit-networks-and-influential-cases",
    title: "Inspect Unit Networks and Influential Cases",
    track: "interpretation",
    level: "intermediate",
    visual: "interpret",
    publishedAt: "2026-07-27",
    tags: ["unit networks", "influential cases", "outlier audit", "group means", "academy step 10"],
    focus: "determining whether a group-level network pattern is broadly shared or driven by a small number of unusual units",
    practicalDecision: "inspect every unit's point, connection magnitude, normalized edge profile, coded-row count, and missingness before relying on a centroid or mean network",
    sensitivity: "repeat the descriptive comparison with each potentially influential unit omitted one at a time and report whether edge rankings, mean locations, or conclusions change",
    evidenceReturn: "open the raw excerpts for the most influential and most typical units and verify that their contrast reflects the phenomenon rather than a coding or boundary error",
    boundary: "An unusual case is not automatically an error and should not be removed to improve separation. Exclusion requires a documented rule, evidence, and a report of how the result changes.",
    pairedSourceLabel: "Systematic review of empirical ENA research in education",
    pairedSourceUrl: "https://doi.org/10.1109/ACCESS.2022.3149812",
  },
  {
    sequence: 11,
    slug: "design-paired-and-repeated-ena-comparisons",
    title: "Design Paired and Repeated ENA Comparisons",
    track: "research-design",
    level: "intermediate",
    visual: "frame",
    publishedAt: "2026-07-28",
    tags: ["paired comparison", "repeated measures", "within-unit change", "dependence", "academy step 11"],
    focus: "comparing the same units across time or conditions without treating repeated networks as unrelated observations",
    practicalDecision: "create a stable composite unit identifier, define time or condition as metadata, preserve the pairing key, and select a paired or repeated-measures inferential strategy before viewing separation",
    sensitivity: "compare complete-pair results with a transparent description of incomplete cases, and inspect whether change is consistent across units or dominated by a few large shifts",
    evidenceReturn: "for one unit, trace both networks back to the corresponding time-specific conversations and verify that the same construct and coding rules were applied",
    boundary: "Pre/post separation does not by itself identify an intervention effect. History, maturation, task differences, missing pairs, and regression can explain within-unit change when the design lacks a counterfactual.",
    pairedSourceLabel: "Algorithmic approaches to qualitative trustworthiness",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_4",
  },
  {
    sequence: 12,
    slug: "quantify-ena-uncertainty",
    title: "Quantify Uncertainty Around ENA Comparisons",
    track: "modeling",
    level: "intermediate",
    visual: "model",
    publishedAt: "2026-07-29",
    tags: ["uncertainty", "bootstrap", "confidence interval", "sampling variation", "academy step 12"],
    focus: "representing the sampling uncertainty around group locations, edge differences, and effect estimates instead of treating plotted means as exact",
    practicalDecision: "state the independent resampling unit, choose an uncertainty procedure consistent with the design, report interval definitions and repetitions, and keep exploratory visualization distinct from formal inference",
    sensitivity: "compare parametric and resampling-based summaries where defensible, then investigate any conclusion that depends on one distributional assumption or one projection coordinate",
    evidenceReturn: "inspect the units contributing to a wide interval and relate uncertainty to sample size, heterogeneity, missingness, and connection sparsity",
    boundary: "A bootstrap cannot rescue a biased sample, invalid codebook, or wrong resampling level. Narrow intervals quantify precision under assumptions; they do not establish construct validity or causal identification.",
    pairedSourceLabel: "Self-efficacy and self-regulation in collaborative design",
    pairedSourceUrl: "https://doi.org/10.3389/fpsyg.2024.1398729",
  },
  {
    sequence: 13,
    slug: "use-means-rotation-for-two-group-questions",
    title: "Use Means Rotation for a Prespecified Two-Group Question",
    track: "modeling",
    level: "intermediate",
    visual: "model",
    publishedAt: "2026-07-30",
    tags: ["means rotation", "two-group contrast", "MR1", "projection choice", "academy step 13"],
    focus: "deciding when the first ENA axis should align with the difference between exactly two prespecified group means",
    practicalDecision: "verify group membership, fit all compared units in one shared model, use means rotation only for the planned two-group contrast, and record the remaining SVD dimension separately",
    sensitivity: "place the means-rotated view beside an exploratory SVD view of the identical normalized connection matrix and distinguish stable edges from rotation-dependent orientation",
    evidenceReturn: "trace the edges loading most strongly on the rotated dimension back to unit networks and excerpts rather than interpreting left and right positions by label alone",
    boundary: "Means rotation makes a planned contrast visible; it does not manufacture independent evidence or test significance. It is inappropriate as a shortcut for three-group or post hoc contrast fishing.",
    pairedSourceLabel: "Segmentation effects in semi-structured interview ENA",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_6",
  },
  {
    sequence: 14,
    slug: "interpret-svd-and-co-registration",
    title: "Interpret SVD Dimensions and Co-registration",
    track: "modeling",
    level: "intermediate",
    visual: "model",
    publishedAt: "2026-07-31",
    tags: ["singular value decomposition", "co-registration", "variance explained", "node placement", "academy step 14"],
    focus: "understanding what SVD axes summarize and whether network node positions are aligned well enough with projected unit coordinates for interpretation",
    practicalDecision: "record variance represented by each displayed dimension, examine co-registration diagnostics, label axes from edge evidence rather than intuition, and avoid treating SVD1 as a group-effect axis",
    sensitivity: "inspect conclusions in the high-dimensional edge table and under an alternative defensible projection so that a two-dimensional orientation is not mistaken for the whole model",
    evidenceReturn: "select units at contrasting coordinates, compare their actual edge vectors, and verify that the plotted node geometry supports the proposed network interpretation",
    boundary: "High variance or high co-registration is not proof that constructs are valid or groups differ. A two-dimensional display necessarily omits variation and may underrepresent relevant edges or cases.",
    pairedSourceLabel: "Internal collaboration scripts under different learning goals",
    pairedSourceUrl: "https://doi.org/10.3389/fpsyg.2024.1410152",
  },
  {
    sequence: 15,
    slug: "reproduce-ena-across-implementations",
    title: "Reproduce an ENA Model Across Implementations",
    track: "modeling",
    level: "intermediate",
    visual: "model",
    publishedAt: "2026-08-01",
    tags: ["cross-implementation parity", "rENA", "jENA", "numerical tolerance", "academy step 15"],
    focus: "checking whether two ENA implementations produce equivalent accumulated connections, normalized vectors, projections, and interpretations under matched settings",
    practicalDecision: "freeze an input file and specification, compare intermediate matrices before plots, align sign-indeterminate axes, define numerical tolerances, and record package versions and defaults",
    sensitivity: "vary one known implementation choice at a time, such as weighting, normalization, or rotation, to identify whether a discrepancy is expected configuration or a defect",
    evidenceReturn: "retain row-level connection contributions and exported edge tables from both runs so every mismatch can be localized before comparing pixels",
    boundary: "Matching screenshots are weak parity evidence, while small floating-point differences are not automatically substantive defects. Equivalence must be judged at the appropriate mathematical and interpretive layers.",
    pairedSourceLabel: "The Mathematical Foundations of Epistemic Network Analysis",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_7",
  },
  {
    sequence: 16,
    slug: "run-window-and-segmentation-sensitivity",
    title: "Run Window and Segmentation Sensitivity as a Model Grid",
    track: "research-design",
    level: "intermediate",
    visual: "frame",
    publishedAt: "2026-08-02",
    tags: ["sensitivity grid", "segmentation", "window size", "robustness", "academy step 16"],
    focus: "separating two coupled context decisions by evaluating a small prespecified grid of segmentation and moving-window alternatives",
    practicalDecision: "define only theoretically plausible segmentations and windows, hold every other setting fixed, name a primary specification, and record all grid results rather than selecting the strongest separation",
    sensitivity: "compare edge-rank stability, unit-coordinate correlation, group-summary direction, and claim wording across the grid, with special attention to individual networks",
    evidenceReturn: "read excerpts around unstable edges under each segmentation-window cell to determine which specification best reflects the activity's actual context",
    boundary: "Robustness is not the number of models tried. A specification that survives many arbitrary alternatives can still be conceptually wrong, and a sensitive result may be informative when the ambiguity is reported.",
    pairedSourceLabel: "Comparing Markov chains and ENA for discourse connections",
    pairedSourceUrl: "https://doi.org/10.3389/feduc.2024.1401996",
  },
  {
    sequence: 17,
    slug: "read-ena-subtraction-networks",
    title: "Read ENA Subtraction Networks Without Overclaiming",
    track: "interpretation",
    level: "intermediate",
    visual: "interpret",
    publishedAt: "2026-08-03",
    tags: ["subtraction network", "difference graph", "shared node positions", "edge contrast", "academy step 17"],
    focus: "interpreting a difference graph as edge-wise subtraction between comparable networks in one shared analytic space",
    practicalDecision: "verify identical codes, node positions, scaling, model settings, and subtraction direction; label which color belongs to which group and retain the original networks beside the difference view",
    sensitivity: "compare the subtraction graph with unit-level edge distributions and a reversed subtraction to ensure that color and sign conventions do not drive the verbal conclusion",
    evidenceReturn: "select the strongest positive and negative edges and recover contributing excerpts from several units in each group rather than one illustrative quotation",
    boundary: "A colored difference edge is not automatically statistically reliable, practically important, or causal. It summarizes modeled mean contrast and can conceal heterogeneous or sparse unit-level evidence.",
    pairedSourceLabel: "Trajectories in Epistemic Network Analysis",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_8",
  },
  {
    sequence: 18,
    slug: "trace-edges-back-to-excerpts",
    title: "Trace Every Interpreted Edge Back to Excerpts",
    track: "interpretation",
    level: "beginner",
    visual: "interpret",
    publishedAt: "2026-08-04",
    tags: ["excerpt traceability", "edge provenance", "interpretive loop", "qualitative evidence", "academy step 18"],
    focus: "building a reproducible route from an interpreted network edge to the units, rows, and source excerpts that contributed to it",
    practicalDecision: "export edge contributions with unit, conversation, row order, code pair, weight, and source-text identifiers, then sample typical, contradictory, and high-contribution examples",
    sensitivity: "compare the interpretation after reading only prominent excerpts with the interpretation after reviewing a systematic spread of units and negative cases",
    evidenceReturn: "store excerpt identifiers and enough surrounding context to evaluate the relation while protecting participant privacy and avoiding decontextualized quotation",
    boundary: "A vivid quotation does not validate a group-level network, and a computed edge does not explain itself. Traceability supports interpretation but still requires a defensible codebook and sampling logic.",
    pairedSourceLabel: "Possible future selves in STEM",
    pairedSourceUrl: "https://doi.org/10.1186/s40594-023-00412-z",
  },
  {
    sequence: 19,
    slug: "report-effect-sizes-and-intervals",
    title: "Report ENA Effect Sizes and Intervals",
    track: "interpretation",
    level: "intermediate",
    visual: "interpret",
    publishedAt: "2026-08-05",
    tags: ["effect size", "confidence interval", "coordinate comparison", "practical importance", "academy step 19"],
    focus: "reporting the magnitude and uncertainty of planned ENA coordinate contrasts alongside plots and p-values",
    practicalDecision: "name the tested dimension and rotation, report group summaries and sample sizes, choose an effect size matching the design, provide an interval, and explain what a coordinate difference represents",
    sensitivity: "check whether the magnitude remains interpretable under robust summaries, paired analysis when required, and a projection that was not selected from the same contrast",
    evidenceReturn: "connect the coordinate effect to the edge loadings and source evidence that distinguish positions so statistical magnitude has substantive meaning",
    boundary: "An effect size on a rotated coordinate is model- and scale-specific. A large standardized value does not establish causal importance, generalizability, or a large difference on every network edge.",
    pairedSourceLabel: "Directed Epistemic Network Analysis",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_9",
  },
  {
    sequence: 20,
    slug: "plan-multiple-group-ena-contrasts",
    title: "Plan Multiple-Group ENA Contrasts and Multiplicity",
    track: "research-design",
    level: "intermediate",
    visual: "frame",
    publishedAt: "2026-08-06",
    tags: ["multiple groups", "planned contrasts", "multiplicity", "shared model", "academy step 20"],
    focus: "comparing three or more groups without forcing them into a two-group means rotation or reporting every favorable pairwise difference",
    practicalDecision: "fit all units in a common reference space, define a small contrast family before inspection, select an omnibus or multiplicity-aware strategy, and distinguish confirmatory from exploratory comparisons",
    sensitivity: "compare conclusions under reasonable multiplicity controls and inspect whether a reported pairwise difference depends on one group, one dimension, or a post hoc rotation",
    evidenceReturn: "review unit distributions and edge evidence for every planned contrast, including null and contradictory patterns rather than only the most separated pair",
    boundary: "More pairwise tests create more opportunities for chance findings. Visual separation among centroids is not an omnibus test, and separate pairwise models cannot be compared as if their axes were one space.",
    pairedSourceLabel: "Reproducible Open Coding Kit and ENA",
    pairedSourceUrl: "https://doi.org/10.1080/21642850.2022.2119144",
  },
  {
    sequence: 21,
    slug: "build-longitudinal-ena-trajectories",
    title: "Build Longitudinal ENA Trajectories in One Space",
    track: "modeling",
    level: "intermediate",
    visual: "model",
    publishedAt: "2026-08-07",
    tags: ["longitudinal trajectory", "shared space", "time ordering", "within-unit path", "academy step 21"],
    focus: "representing successive network states as ordered paths while keeping every time point co-registered in one analytic space",
    practicalDecision: "define the repeated unit and ordered time field, choose cumulative or separate time-state networks, fit a shared projection, and state what a segment between two points means",
    sensitivity: "compare trajectories under alternative defensible time bins and inspect whether direction, turning points, and endpoints persist when sparsely observed periods are handled transparently",
    evidenceReturn: "select one trajectory segment and recover the newly accumulated or changed connections and source events responsible for the movement",
    boundary: "A path on a plot is not a literal cognitive journey or a complete inferential model. Unequal observation, cumulative construction, smoothing, and projection can shape apparent speed and direction.",
    pairedSourceLabel: "Parsimonious Removal with Interpretive Alignment",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_10",
  },
  {
    sequence: 22,
    slug: "choose-directed-or-ordered-network-analysis",
    title: "Choose Directed or Ordered Network Analysis When Sequence Matters",
    track: "modeling",
    level: "intermediate",
    visual: "model",
    publishedAt: "2026-08-08",
    tags: ["ordered network analysis", "directed edges", "sequence", "transition logic", "academy step 22"],
    focus: "deciding whether the research question concerns undirected association, directed ordering, or a stricter transition process",
    practicalDecision: "write the temporal estimand first, verify row order, define edge direction and window, prevent boundary leakage, and choose ENA, directed ENA, ONA, or a transition model accordingly",
    sensitivity: "fit an undirected benchmark and a direction-preserving model on the same coded records, then identify which conclusions depend specifically on order",
    evidenceReturn: "trace a directional edge to multiple ordered source sequences and check whether reverse-order examples are absent, rare, or excluded by preprocessing",
    boundary: "An arrow does not prove causation, and temporal precedence within a coded window may not represent a meaningful transition. Directional models demand stronger ordering and context justification.",
    pairedSourceLabel: "Teacher professional vision across biology and mathematics",
    pairedSourceUrl: "https://doi.org/10.3389/feduc.2023.1253459",
  },
  {
    sequence: 23,
    slug: "prepare-multimodal-data-for-ena",
    title: "Prepare Multimodal Events for ENA",
    track: "data-preparation",
    level: "intermediate",
    visual: "prepare",
    publishedAt: "2026-08-10",
    tags: ["multimodal data", "event alignment", "sensor traces", "observation streams", "academy step 23"],
    focus: "aligning speech, action, sensor, screen, or spatial events on a defensible common timeline before modeling cross-modal connections",
    practicalDecision: "retain raw timestamps, document clock offsets and aggregation intervals, define modality-specific codes, choose an alignment tolerance, and separate missing observation from coded absence",
    sensitivity: "shift the alignment tolerance within plausible measurement error and inspect whether cross-modal edges or group conclusions change disproportionately",
    evidenceReturn: "replay or inspect the original multimodal episode for high-weight cross-modal edges and confirm that synchronization represents one meaningful activity context",
    boundary: "Temporal alignment does not make modalities commensurable or validate automated detectors. Device error, observation gaps, privacy constraints, and unequal sampling rates remain part of the evidence model.",
    pairedSourceLabel: "Curricular design and student STEM identity change",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_11",
  },
  {
    sequence: 24,
    slug: "validate-automated-codes-before-ena",
    title: "Validate Automated Codes Before They Enter ENA",
    track: "data-preparation",
    level: "intermediate",
    visual: "prepare",
    publishedAt: "2026-08-11",
    tags: ["automated coding", "classifier validation", "error propagation", "human review", "academy step 24"],
    focus: "evaluating whether model-generated labels are accurate enough for relational analysis and how classification errors propagate into edges",
    practicalDecision: "retain prediction scores, create a human-labeled evaluation set, report per-code precision and recall, inspect subgroup performance, choose thresholds before ENA, and review uncertain or out-of-domain cases",
    sensitivity: "rebuild networks under plausible thresholds and with human-corrected labels for the evaluation subset to identify edges that are especially vulnerable to false positives or negatives",
    evidenceReturn: "trace each interpreted automated-code edge to source text and classifier outputs, including errors and manual overrides rather than only successful examples",
    boundary: "Good aggregate classification performance does not guarantee reliable rare-code connections or fairness across groups. ENA can magnify systematic co-classification errors into persuasive network patterns.",
    pairedSourceLabel: "Thematic-cognitive ENA of children's writing",
    pairedSourceUrl: "https://doi.org/10.3389/fpsyg.2025.1494111",
  },
  {
    sequence: 25,
    slug: "handle-missing-data-and-exclusions",
    title: "Handle Missing Data and Exclusions Transparently",
    track: "data-preparation",
    level: "beginner",
    visual: "prepare",
    publishedAt: "2026-08-13",
    tags: ["missing data", "exclusion rules", "zero versus missing", "attrition", "academy step 25"],
    focus: "distinguishing a true code absence, an all-zero observed unit, an unobserved period, a malformed row, and an excluded case",
    practicalDecision: "define each missingness state, preserve raw rows, produce a flow table from intake to analyzed units, apply prespecified exclusions, and never silently convert unknown judgments to zero",
    sensitivity: "compare complete-case results with at least one defensible missing-data or inclusion scenario and explain which units, edges, and group balances change",
    evidenceReturn: "audit a sample from every exclusion category against the source record and documented rule, then retain identifiers in a protected exclusion ledger",
    boundary: "No imputation or sensitivity analysis can fully recover information that was never observed. Missingness mechanisms and differential attrition limit interpretation even when software accepts a complete matrix.",
    pairedSourceLabel: "Self-regulated learning in Betty's Brain",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_13",
  },
  {
    sequence: 26,
    slug: "preregister-an-ena-decision-record",
    title: "Preregister an ENA Decision Record",
    track: "research-design",
    level: "beginner",
    visual: "frame",
    publishedAt: "2026-08-14",
    tags: ["preregistration", "decision record", "confirmatory analysis", "research transparency", "academy step 26"],
    focus: "recording the relational question and consequential ENA choices before outcome patterns or group separation are inspected",
    practicalDecision: "state hypotheses, units, conversations, ordering, codes, window, weighting, normalization, rotation, contrasts, exclusions, inference, sensitivity checks, and the boundary between confirmatory and exploratory work",
    sensitivity: "timestamp the primary plan, log every deviation with a reason, and show whether the central claim depends on an unplanned model choice",
    evidenceReturn: "attach versioned codebooks, blank analysis shells, and source-data provenance so the preregistration describes an executable evidence chain rather than a vague intention",
    boundary: "Preregistration does not make a weak design valid or prohibit learning from data. Its value is separating what was planned from what was discovered and making researcher degrees of freedom visible.",
    pairedSourceLabel: "Desktop versus VR for collaborative sensemaking",
    pairedSourceUrl: "https://doi.org/10.3389/frvir.2025.1570383",
  },
  {
    sequence: 27,
    slug: "compare-ena-normalization-choices",
    title: "Compare ENA Normalization Choices",
    track: "modeling",
    level: "intermediate",
    visual: "model",
    publishedAt: "2026-08-15",
    tags: ["normalization choice", "sphere normalization", "connection magnitude", "estimand", "academy step 27"],
    focus: "deciding whether analysis should emphasize relative connection composition, total connection magnitude, or another explicitly defined quantity",
    practicalDecision: "inspect raw connection vectors and exposure, justify sphere normalization or an alternative from the question, document zero-network handling, and avoid mixing coordinates from separately fitted spaces",
    sensitivity: "compare normalized and unnormalized edge evidence while controlling for observation amount and explain which substantive statements change when magnitude is retained or removed",
    evidenceReturn: "select units whose positions change most after normalization and inspect whether differences reflect discourse amount, code density, or genuinely different relational profiles",
    boundary: "Normalization is not a neutral cleanup step. Sphere normalization removes vector length, can amplify sparse profiles, and cannot replace a design-level solution to unequal exposure or missing observation.",
    pairedSourceLabel: "Single-case ENA in lifelong learning",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_14",
  },
  {
    sequence: 28,
    slug: "define-a-zero-network-policy",
    title: "Define a Zero-Network Policy Before Modeling",
    track: "data-preparation",
    level: "intermediate",
    visual: "prepare",
    publishedAt: "2026-08-16",
    tags: ["zero network", "empty vector", "sparse data", "normalization failure", "academy step 28"],
    focus: "handling units that have observed rows but no modeled code co-occurrences under the chosen window and code set",
    practicalDecision: "distinguish observed all-zero units from missing units, count why connections are absent, decide whether and how they enter plots and tests, and document software behavior before normalization",
    sensitivity: "report results with the prespecified zero-network policy and a defensible alternative, especially when zero networks are unevenly distributed across groups",
    evidenceReturn: "inspect the underlying rows for every zero network to determine whether it reflects genuine absence, single-code activity, coding failure, short conversations, or preprocessing error",
    boundary: "A zero vector has no direction for sphere normalization. Silently dropping it changes the analyzed population, while inventing tiny values creates relations not present in the evidence.",
    pairedSourceLabel: "MOOC learning sentiment networks",
    pairedSourceUrl: "https://doi.org/10.19173/irrodl.v26i1.7965",
  },
  {
    sequence: 29,
    slug: "export-an-ena-reproducibility-bundle",
    title: "Export an ENA Reproducibility Bundle",
    track: "data-preparation",
    level: "beginner",
    visual: "prepare",
    publishedAt: "2026-08-17",
    tags: ["reproducibility bundle", "provenance", "export artifacts", "file hashes", "academy step 29"],
    focus: "packaging enough data, metadata, decisions, code, and outputs for another analyst to audit and rerun the model",
    practicalDecision: "export de-identified source-ready data, codebook, decision record, software lockfile, executable script, settings, edge tables, unit coordinates, diagnostics, exclusions, and a manifest with hashes",
    sensitivity: "rerun the bundle in a clean directory or environment and compare intermediate tables and model outputs within documented tolerances",
    evidenceReturn: "include stable source-row identifiers and an access-controlled route to qualitative evidence so public reproducibility does not compromise participant confidentiality",
    boundary: "A bundle is not reproducible if it depends on hidden clicks, mutable URLs, undocumented manual edits, private fonts, or unavailable source fields. Openness must still respect consent and privacy.",
    pairedSourceLabel: "Counting the Game with event-aware ENA",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_15",
  },
  {
    sequence: 30,
    slug: "write-a-complete-ena-methods-section",
    title: "Write a Complete ENA Methods Section",
    track: "research-design",
    level: "intermediate",
    visual: "frame",
    publishedAt: "2026-08-18",
    tags: ["methods reporting", "ENA specification", "reproducible manuscript", "analytic transparency", "academy step 30"],
    focus: "reporting the full chain from research design and qualitative coding through accumulation, normalization, projection, comparison, and sensitivity analysis",
    practicalDecision: "name participants and sampling, data source, segmentation, coding and validation, units, conversations, row order, window, weighting, normalization, rotation, software, exclusions, statistics, and interpretive return",
    sensitivity: "give a second analyst only the Methods draft and available files, then record every configuration detail they must guess and repair the manuscript or supplement",
    evidenceReturn: "cite the codebook and provenance artifacts and explain how interpreted edges were checked against source evidence rather than describing only the software interface",
    boundary: "A long Methods section can still be irreproducible if it omits defaults or hides post hoc decisions. Reporting detail does not compensate for weak design, but it lets readers evaluate that design.",
    pairedSourceLabel: "Shared agency in Knowledge Building discourse",
    pairedSourceUrl: "https://doi.org/10.58459/rptel.2026.21006",
  },
  {
    sequence: 31,
    slug: "write-ena-results-with-layered-evidence",
    title: "Write ENA Results With Layered Evidence",
    track: "interpretation",
    level: "intermediate",
    visual: "interpret",
    publishedAt: "2026-08-19",
    tags: ["results reporting", "layered evidence", "network statistics", "qualitative excerpts", "academy step 31"],
    focus: "presenting descriptive data, model diagnostics, statistical comparisons, edge interpretations, and qualitative evidence without collapsing them into one claim",
    practicalDecision: "report the analyzed sample and exposure first, then projection diagnostics, planned statistics with effects and intervals, network differences, representative and contradictory excerpts, and sensitivity outcomes",
    sensitivity: "remove the figure and check whether the text still identifies the exact model and evidence; then remove the prose and check whether the figure caption prevents unsupported visual inference",
    evidenceReturn: "for every substantive edge claim, retain unit coverage and excerpt identifiers so examples illustrate a systematic pattern rather than replace it",
    boundary: "Results should not introduce unreported models, causal explanations, or universal language. Network position, edge contrast, statistical uncertainty, and contextual meaning are related but distinct evidence layers.",
    pairedSourceLabel: "Longitudinal preschool curiosity trajectories",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_16",
  },
  {
    sequence: 32,
    slug: "audit-causal-language-in-ena-studies",
    title: "Audit Causal Language in ENA Studies",
    track: "interpretation",
    level: "beginner",
    visual: "interpret",
    publishedAt: "2026-08-20",
    tags: ["causal language", "claim audit", "observational design", "counterfactual", "academy step 32"],
    focus: "matching verbs such as differs, predicts, changes, influences, and causes to the identification strength of the study design",
    practicalDecision: "write a design-to-claim table, identify the exposure and counterfactual, mark observed associations and randomized contrasts separately, and replace causal verbs that the design cannot support",
    sensitivity: "ask whether plausible selection, history, measurement, coding, attrition, or task explanations could produce the same network difference and report how they were addressed",
    evidenceReturn: "pair each claim with the exact comparison, edge or coordinate evidence, uncertainty, and source excerpts, then state what additional design would be needed for causality",
    boundary: "ENA is a representation and comparison method, not a causal identification strategy. Randomization or strong quasi-experimental assumptions must come from the research design and analysis beyond the network picture.",
    pairedSourceLabel: "Older adults' conceptions of AI-supported learning",
    pairedSourceUrl: "https://doi.org/10.1186/s40561-026-00443-3",
  },
  {
    sequence: 33,
    slug: "run-an-ena-peer-review-readiness-audit",
    title: "Run an ENA Peer-Review Readiness Audit",
    track: "research-design",
    level: "intermediate",
    visual: "frame",
    publishedAt: "2026-08-21",
    tags: ["peer review readiness", "method audit", "reproducibility", "claim boundary", "academy step 33"],
    focus: "checking whether a complete ENA study lets an independent reviewer follow every claim from design to source evidence and rerunnable artifacts",
    practicalDecision: "audit alignment, code validity, units and dependence, context windows, transformations, diagnostics, inference, effect reporting, qualitative return, sensitivity, ethics, data availability, and figure captions",
    sensitivity: "assign a skeptical reader to reproduce one main result and challenge one interpretation without author coaching, then classify every failure as missing evidence, missing documentation, or analytic defect",
    evidenceReturn: "build a claim ledger that links each abstract and discussion statement to a result, model specification, unit distribution, source excerpt set, and limitation",
    boundary: "Passing a checklist does not guarantee publication or truth. It reduces avoidable opacity and overclaiming, while substantive validity still depends on theory, evidence quality, design, and scholarly judgment.",
    pairedSourceLabel: "Social presence and MOOC learner network position",
    pairedSourceUrl: "https://doi.org/10.1007/978-3-030-67788-6_17",
  },
];

function buildLesson(spec: BackfillLessonSpec): AcademyLesson {
  const id = `academy-${String(spec.sequence).padStart(3, "0")}`;
  const topic = spec.title.replace(/[.:]/g, "");

  return {
    id,
    slug: spec.slug,
    sequence: spec.sequence,
    title: spec.title,
    track: spec.track,
    level: spec.level,
    durationMinutes: spec.level === "beginner" ? 25 : 35,
    publishedAt: spec.publishedAt,
    tags: spec.tags,
    visual: spec.visual,
    visualAlt: `A structured ENA Academy workflow for ${spec.focus}`,
    shortSummary: `Use the shared synthetic design-talk dataset to practise ${spec.focus}, document the decision, test a defensible alternative, and keep every interpretation tied to source evidence.`,
    introduction: [
      `${spec.title} addresses ${spec.focus}. This decision belongs in the evidence model, not in a late formatting pass. It affects which coded observations can contribute to a network, what the plotted coordinates represent, and how confidently a comparison can be interpreted. The lesson extends the same eight-team synthetic design-talk case used throughout the Academy so that only the target decision changes while the broader learning context remains stable.`,
      `You will work from the source CSV, codebook, and blank decision record. The synthetic file is intentionally small and balanced; it supports transparent inspection but no real-world inference. Your goal is to leave an audit trail that another analyst can rerun: the primary choice, its theoretical rationale, one prespecified sensitivity check, the resulting network evidence, and the claim boundary.`,
    ],
    learningObjectives: [
      `${topic}: explain the target decision in relation to the relational research question and modeled estimand.`,
      `${topic}: implement and compare a primary specification with one defensible sensitivity alternative.`,
      `${topic}: trace the resulting network interpretation to unit-level rows and write an evidence-bounded conclusion.`,
    ],
    caseStudy: {
      title: `${spec.title} in the design-talk case`,
      text: `Eight fictional teacher-design teams discuss goals, student evidence, strategies, tradeoffs, and revisions. Four are labeled baseline and four scaffolded, with six ordered utterances per team. The recurring question is whether the two conditions organize these ideas differently. For this lesson, the analytic focus is ${spec.focus}; the tiny balanced file makes every contributing row inspectable while preventing invented population claims.`,
    },
    steps: [
      {
        title: "Restate the relational estimand",
        text: `Write one sentence naming the unit network, the comparison, and the contextual relation represented by a connection. Then explain how ${spec.focus} can change that estimand. Keep the distinction between raw observation, coded evidence, accumulated connection, normalized vector, projected coordinate, and substantive claim visible. If the target choice cannot be linked to the question, pause before opening a model.`,
        checkpoint: "The decision record names one unit, one bounded context, one comparison, and the exact relation a weighted edge represents.",
      },
      {
        title: "Freeze the shared baseline specification",
        text: `Record the dataset filename and hash; team_id as unit; conversation_id as conversation; line_number as order; condition as metadata; the five binary code columns; the current window, weighting, normalization, and rotation; exclusions; and software version. This frozen baseline prevents an apparent change from being attributed to ${spec.focus} when another setting changed at the same time.`,
        checkpoint: "A second analyst can recreate the baseline model without relying on interface memory or undocumented defaults.",
      },
      {
        title: "Implement the primary decision",
        text: `Apply this prespecified procedure: ${spec.practicalDecision}. Save the configuration before inspecting the preferred group pattern. Export unit coordinates, accumulated and normalized edge tables, group summaries, and diagnostics rather than keeping only a screenshot. Mark any manual judgment with a date and rationale so later review can distinguish planned configuration from reactive adjustment.`,
        checkpoint: "The primary run has a dated configuration, machine-readable outputs, and a rationale written before substantive interpretation.",
      },
      {
        title: "Inspect units before group averages",
        text: `Review all eight unit networks, their coded-row exposure, connection magnitudes, and positions. Identify all-zero, sparse, or influential cases and verify that every unit belongs to the intended condition. A mean network can look coherent even when only one team supplies an edge, so record unit coverage for the strongest visible relations and inspect whether within-group heterogeneity contradicts a simple group story.`,
        checkpoint: "Every interpreted group edge has a unit-coverage count, and no case was silently dropped because its pattern was inconvenient.",
      },
      {
        title: "Run the planned sensitivity check",
        text: `Without changing unrelated settings, ${spec.sensitivity}. Save the primary and alternative outputs side by side and compare connection ranks, unit coordinates, group means, diagnostics, and the wording of the conclusion. Sensitivity analysis is not a search for the most separated plot; report stable, weakened, reversed, and ambiguous patterns with equal visibility.`,
        checkpoint: "The record states exactly what changed, what stayed fixed, and whether the main interpretation survives the alternative.",
      },
      {
        title: "Return from edges to evidence",
        text: `Close the interpretive loop: ${spec.evidenceReturn}. Read enough surrounding rows to recover the conversational context and examine counterexamples, not only quotations that fit the network. Preserve team, conversation, and row identifiers in the audit output. If the edge interpretation conflicts with the excerpts, revise the interpretation or investigate the coding and window rather than trusting the graph.`,
        checkpoint: "The interpretation cites traceable rows from multiple units and records at least one contradictory or boundary case.",
      },
      {
        title: "Write the decision and claim boundary",
        text: `Write three layers in order: the observed source evidence, the modeled pattern under the primary specification, and the explanation the synthetic design cannot establish. Include the sensitivity outcome and this boundary: ${spec.boundary} End with the exact files needed to reproduce the lesson and a note that the exercise demonstrates workflow logic rather than a finding about real teachers or scaffolds.`,
        checkpoint: "The final paragraph separates observation, model output, interpretation, uncertainty, and non-causal limitation in explicit language.",
      },
    ],
    coreIdeas: [
      `${spec.title} is part of the model specification and therefore changes what an ENA result can mean.`,
      "A defensible sensitivity check varies one consequential choice while preserving a frozen baseline and all alternative results.",
      "Interpretation is complete only when network features can be traced to units, ordered rows, code definitions, and source evidence.",
    ],
    analysisChecks: [
      "Does the primary decision follow from the relational question rather than from the most attractive group separation?",
      "Were units, conversations, codes, order, weighting, normalization, rotation, and exclusions held constant where required?",
      "Do unit-level evidence, diagnostics, and sensitivity results support the wording of the group-level interpretation?",
      "Could another analyst rerun the model and locate every interpreted edge in the source-ready data and codebook?",
    ],
    methodBoundary: `${spec.boundary} The shared Academy dataset contains only eight fictional teams and forty-eight authored rows. It is designed to expose every model decision and evidence link, not to estimate an intervention effect, validate a universal default, or represent actual teachers. Transfer the workflow to real research only after addressing sampling, consent, de-identification, coding validity, dependence, uncertainty, and the substantive meaning of co-occurrence in that setting.`,
    sources: [
      tutorialSource,
      { label: spec.pairedSourceLabel, url: spec.pairedSourceUrl },
    ],
    downloads: [...sharedDownloads],
  };
}

export const backfillAcademyLessons: AcademyLesson[] = backfillLessonSpecs.map(buildLesson);
