import type { NewsArticle, NewsType } from "./news-types";

interface BackfillNewsSpec {
  id: number;
  slug: string;
  headline: string;
  paperTitle: string;
  authors: string[];
  venue: string;
  year: number;
  type: NewsType;
  tags: string[];
  createdAt: string;
  doi: string;
  publisherUrl: string;
  researchFocus: string;
  evidence: string;
  method: string;
  reportedPattern: string;
  boundary: string;
  contribution: string;
  scene: string;
}

const backfillNewsSpecs: BackfillNewsSpec[] = [
  {
    id: 8,
    slug: "ena-tutorial-dynamic-network-models",
    headline: "The foundational ENA tutorial connected coded evidence, networks, and comparison",
    paperTitle: "A Tutorial on Epistemic Network Analysis: Analyzing the Structure of Connections in Cognitive, Social, and Interaction Data",
    authors: ["David Williamson Shaffer", "Wesley Collier", "A. R. Ruis"],
    venue: "Journal of Learning Analytics",
    year: 2016,
    type: "journal",
    tags: ["foundational tutorial", "dynamic networks", "coded data", "network comparison", "quantitative ethnography"],
    createdAt: "2026-07-23",
    doi: "10.18608/jla.2016.33.3",
    publisherUrl: "https://learning-analytics.info/index.php/JLA/article/view/4329",
    researchFocus: "how researchers can identify, quantify, visualize, and compare patterns of association among a fixed set of coded elements",
    evidence: "The article is a methodological tutorial rather than a population study. It develops worked explanations of unit networks, connection strengths, shared node positions, and changes in network composition over time.",
    method: "The workflow begins with segmented and coded records, accumulates code co-occurrences for defined units, represents each unit as a weighted network, and places comparable networks in a common low-dimensional space.",
    reportedPattern: "The tutorial shows that network structure can be compared directly and through summary statistics when the modeled associations have a defensible meaning in the source context.",
    boundary: "A worked method cannot validate the constructs, codes, conversation boundaries, sampling design, or causal interpretation supplied by a later analyst.",
    contribution: "It established a practical bridge between qualitative interpretation and mathematically coordinated network comparison that remains central to ENA practice.",
    scene: "researchers connecting coded excerpts to a transparent network model on a shared analysis table",
  },
  {
    id: 9,
    slug: "quantitative-ethnography-scoping-review",
    headline: "A field scan mapped opportunities and recurring trustworthiness challenges in QE",
    paperTitle: "Scoping the Emerging Field of Quantitative Ethnography: Opportunities, Challenges and Future Directions",
    authors: ["Rogers Kaliisa", "Kamila Misiejuk", "Golnaz Arastoopour Irgens", "Morten Misfeldt"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["scoping review", "field development", "methodological transparency", "interpretability", "research synthesis"],
    createdAt: "2026-07-24",
    doi: "10.1007/978-3-030-67788-6_1",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_1",
    researchFocus: "which practices, opportunities, and unresolved challenges characterized the emerging field of quantitative ethnography",
    evidence: "The authors scoped 60 quantitative ethnography studies and examined how researchers connected qualitative analysis, coding, computation, and interpretation across the reviewed corpus.",
    method: "The synthesis organized recurring methodological choices rather than pooling effect sizes. It traced how studies grounded codes, documented validity and consistency, used quantitative models, and returned results to qualitative meaning.",
    reportedPattern: "Grounded analysis and attention to code validity were common, while interpretability, methodological consistency, and clearer reporting remained visible field-level challenges.",
    boundary: "A scoping review describes the accessible literature and its reporting practices; it does not prove that one workflow is universally superior or that omitted studies followed the same pattern.",
    contribution: "The review offers a field-level checklist for making qualitative grounding, computation, and interpretive claims visible in one evidence chain.",
    scene: "a research team sorting many study cards into evidence, coding, modeling, and interpretation pathways",
  },
  {
    id: 10,
    slug: "temporal-collaboration-physical-learning-spaces",
    headline: "Temporal ENA exposed how table shape, group size, and gender intersected in collaboration",
    paperTitle: "Studying Collaboration Dynamics in Physical Learning Spaces: Considering the Temporal Perspective through Epistemic Network Analysis",
    authors: ["Milica Vujovic", "Ishari Amarasinghe", "Davinia Hernández-Leo"],
    venue: "Sensors",
    year: 2021,
    type: "journal",
    tags: ["physical learning spaces", "temporal collaboration", "table shape", "engineering design", "observational coding"],
    createdAt: "2026-07-25",
    doi: "10.3390/s21092898",
    publisherUrl: "https://www.mdpi.com/1424-8220/21/9/2898",
    researchFocus: "whether a temporal view of coded activity could clarify how physical table shape relates to collaboration under different group-size and gender conditions",
    evidence: "Students completed engineering design tasks while researchers observed explanation, discussion, non-verbal interaction, and interaction with physical artefacts.",
    method: "The study treated the order and co-occurrence of observed actions as evidence about collaboration dynamics, then used ENA to compare relational patterns across learning-space configurations.",
    reportedPattern: "The reported networks suggest that table shape was associated with different student behaviours when group size and gender were considered rather than ignored.",
    boundary: "The observational design, specific tasks, participant composition, and bundled spatial conditions do not isolate a universal causal effect of furniture shape.",
    contribution: "It demonstrates why learning-space evaluation can benefit from temporal relational evidence instead of relying only on counts or end-of-task outcomes.",
    scene: "student engineering teams collaborating around differently shaped tables while temporal action links are recorded",
  },
  {
    id: 11,
    slug: "topic-modeling-code-discovery",
    headline: "Topic modeling helped discover candidate codes but could not replace human interpretation",
    paperTitle: "Using Topic Modeling for Code Discovery in Large Scale Text Data",
    authors: ["Zhiqiang Cai", "Amanda Siebert-Evenstone", "Brendan Eagan", "David Williamson Shaffer"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["topic modeling", "code discovery", "large-scale text", "human interpretation", "algorithmic coding"],
    createdAt: "2026-07-26",
    doi: "10.1007/978-3-030-67788-6_2",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_2",
    researchFocus: "whether unsupervised topic models can support the discovery of qualitative codes in large textual corpora",
    evidence: "The paper compares machine-generated topics with an existing human coding framework and inspects how topic words and human codes align across documents.",
    method: "Rather than treating a topic label as a finished code, the workflow examines topic-word lists as prompts for analysts who must still define constructs, inclusion rules, and contextual meaning.",
    reportedPattern: "Topics often mixed several human codes, and words linked to one human code could appear across multiple topics; concise topic-word lists were more useful as discovery aids than direct replacements for codes.",
    boundary: "Alignment with one coded corpus does not establish that a topic model will recover valid constructs in another domain, language, or preprocessing pipeline.",
    contribution: "The paper locates automation at a defensible point in qualitative work: generating inspectable candidates while leaving construct judgment and validation with researchers.",
    scene: "analysts comparing algorithmic word clusters with human-coded excerpts on two linked panels",
  },
  {
    id: 12,
    slug: "ena-education-systematic-review",
    headline: "A systematic review charted how ENA has been used across education research",
    paperTitle: "A Systematic Literature Review of Empirical Research on Epistemic Network Analysis in Education",
    authors: ["Ramy Elmoazen", "Mohammed Saqr", "Matti Tedre", "Laura Hirsto"],
    venue: "IEEE Access",
    year: 2022,
    type: "journal",
    tags: ["systematic review", "education research", "empirical applications", "reporting quality", "method trends"],
    createdAt: "2026-07-27",
    doi: "10.1109/ACCESS.2022.3149812",
    publisherUrl: "https://ieeexplore.ieee.org/document/9706446/",
    researchFocus: "how empirical education studies have designed, implemented, and reported Epistemic Network Analysis",
    evidence: "The review assembles published education applications and categorizes their settings, data sources, analytic purposes, and methodological reporting.",
    method: "Its contribution is descriptive synthesis: locating eligible studies, extracting comparable design features, and identifying recurring application patterns and gaps rather than estimating a pooled intervention effect.",
    reportedPattern: "The literature shows ENA applied across multiple educational domains and data types, alongside uneven methodological detail and opportunities for stronger reporting and reproducibility.",
    boundary: "The conclusions depend on database coverage, eligibility rules, publication practices, and the information authors reported; absence from the review is not evidence that a practice never occurred.",
    contribution: "The synthesis gives new researchers a map of established use cases and highlights where transparent specifications are needed for cumulative evidence.",
    scene: "an evidence-review team mapping education studies across domains, data sources, and ENA decisions",
  },
  {
    id: 13,
    slug: "algorithmic-qualitative-trustworthiness",
    headline: "Human–NLP collaboration made three dimensions of qualitative trustworthiness inspectable",
    paperTitle: "Establishing Trustworthiness Through Algorithmic Approaches to Qualitative Research",
    authors: ["Ha Nguyen", "June Ahn", "Ashlee Belgrave", "Jiwon Lee", "Lora Cawelti", "Ha Eun Kim", "Yenda Prado", "Rossella Santagata", "Adriana Villavicencio"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["qualitative trustworthiness", "natural language processing", "human-in-the-loop", "COVID-19 educators", "audit trail"],
    createdAt: "2026-07-28",
    doi: "10.1007/978-3-030-67788-6_4",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_4",
    researchFocus: "how natural language processing combined with researcher interpretation can strengthen credibility, dependability, and confirmability in qualitative analysis",
    evidence: "The workflow is illustrated through a time-sensitive study of educators' experiences during the 2020 COVID-19 pandemic.",
    method: "Algorithmic pattern finding and human review are documented as complementary stages, allowing researchers to inspect candidate groupings, challenge interpretations, and record how analytic decisions evolved.",
    reportedPattern: "The case demonstrates practical affordances for efficient analysis while keeping human examination central to the claims and to the trustworthiness audit.",
    boundary: "A successful illustration does not make NLP output inherently credible, transferable, or unbiased; trustworthiness still depends on data quality, researcher reflexivity, validation, and transparent disagreement handling.",
    contribution: "It reframes computational assistance as part of a visible qualitative process rather than an opaque substitute for interpretation.",
    scene: "qualitative researchers reviewing educator narratives beside transparent NLP clusters and an audit notebook",
  },
  {
    id: 14,
    slug: "self-efficacy-regulation-collaborative-design",
    headline: "ENA traced different self-regulation configurations across design students' self-efficacy groups",
    paperTitle: "How do students of different self-efficacy regulate learning in collaborative design activities? An epistemic network analysis approach",
    authors: ["Peng Chen", "Dong Yang", "Jari Lavonen", "Ahmed Hosny Saleh Metwally", "Xin Tang"],
    venue: "Frontiers in Psychology",
    year: 2024,
    type: "journal",
    tags: ["self-efficacy", "self-regulated learning", "collaborative design", "written reflection", "developmental trajectory"],
    createdAt: "2026-07-29",
    doi: "10.3389/fpsyg.2024.1398729",
    publisherUrl: "https://www.frontiersin.org/articles/10.3389/fpsyg.2024.1398729/full",
    researchFocus: "how self-regulated learning characteristics and trajectories differed among university design students grouped by initial self-efficacy",
    evidence: "Sixty students in a collaborative design course were classified into high, mixed, and low self-efficacy groups, and their written reflections supplied the coded evidence.",
    method: "ENA modeled connections among self-regulation behaviours across anticipation, performance, and reflection-related activity rather than reducing each construct to an isolated frequency.",
    reportedPattern: "The high-self-efficacy group showed more performance and self-reflection characteristics, earlier interest and task-value recognition, later cognitive and metacognitive strategy use, and an anticipation–behaviour–reflection loop.",
    boundary: "Grouping students on an initial measure and analyzing course reflections supports relational association and temporal description, not proof that self-efficacy caused the observed regulatory configuration.",
    contribution: "The study shows how reflection data can represent the organization of self-regulation while retaining a clear boundary around causal and instructional claims.",
    scene: "collaborative design students reflecting as anticipation, action, and reflection form different network loops",
  },
  {
    id: 15,
    slug: "interview-segmentation-sensitivity",
    headline: "Segmentation sensitivity was modest overall but substantial for some interview networks",
    paperTitle: "Exploring the Effects of Segmentation on Semi-structured Interview Data with Epistemic Network Analysis",
    authors: ["Szilvia Zörgő", "Zachari Swiecki", "A. R. Ruis"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["segmentation sensitivity", "semi-structured interviews", "individual networks", "model robustness", "narrative data"],
    createdAt: "2026-07-30",
    doi: "10.1007/978-3-030-67788-6_6",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_6",
    researchFocus: "how alternative segmentation decisions affect population-level and individual ENA features in continuous interview narratives",
    evidence: "The authors resegmented semi-structured interview narratives and compared resulting network features at more than one analytic level.",
    method: "The proposed sensitivity workflow treats segmentation as a model decision that can be varied systematically while the underlying narratives and coding framework remain inspectable.",
    reportedPattern: "Segmentation changes did not necessarily alter overall model features, yet their effects on particular individual networks could be substantial.",
    boundary: "The magnitude and direction of sensitivity depend on the narrative structure, code distribution, window, and segmentation alternatives used in this dataset.",
    contribution: "The method turns an often-hidden preprocessing choice into an explicit robustness check before analysts interpret individual cases or group summaries.",
    scene: "the same interview transcript divided into alternative segments that produce visibly different individual networks",
  },
  {
    id: 16,
    slug: "learning-goals-collaboration-scripts",
    headline: "Learning goals changed how collaboration scriptlets connected, even when selections looked similar",
    paperTitle: "How do different goals affect students’ internal collaboration script configurations? Results of an epistemic network analysis study",
    authors: ["Tugce Özbek", "Martin Greisel", "Christina Wekerle", "Andreas Gegenfurtner", "Ingo Kollar"],
    venue: "Frontiers in Psychology",
    year: 2024,
    type: "journal",
    tags: ["collaboration scripts", "learning goals", "preservice teachers", "CSCL", "knowledge acquisition"],
    createdAt: "2026-07-31",
    doi: "10.3389/fpsyg.2024.1410152",
    publisherUrl: "https://www.frontiersin.org/articles/10.3389/fpsyg.2024.1410152/full",
    researchFocus: "whether inducing learning goals changes the configuration of internal collaboration scriptlets during computer-supported collaborative learning",
    evidence: "A total of 233 preservice teachers collaborated in dyads to analyze an authentic classroom problem using educational evidence, with scriptlets measured before and after collaboration.",
    method: "The experiment compared a learning-goal induction condition with a no-induction condition, while ENA examined combinations of selected scriptlets and a separate measure assessed acquired knowledge.",
    reportedPattern: "Goal induction did not change which kinds of scriptlets participants selected, but it produced different relations among scriptlets and was accompanied by greater knowledge about educational theories and evidence.",
    boundary: "The intervention and task support a condition-specific experimental contrast; they do not establish that every goal prompt will reorganize collaboration or improve outcomes in other settings.",
    contribution: "The result illustrates ENA's value when isolated category counts appear similar but their configuration carries theoretically important information.",
    scene: "preservice-teacher dyads linking evidence and collaboration scriptlets under two goal conditions",
  },
  {
    id: 17,
    slug: "mathematical-foundations-ena",
    headline: "A formal account linked ENA's network pictures to its high-dimensional mathematics",
    paperTitle: "The Mathematical Foundations of Epistemic Network Analysis",
    authors: ["Dale Bowman", "Zachari Swiecki", "Zhiqiang Cai", "Yeyu Wang", "Brendan Eagan", "Jeff Linderoth", "David Williamson Shaffer"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["mathematical foundations", "matrix transformations", "co-registration", "dimensional reduction", "unit networks"],
    createdAt: "2026-08-01",
    doi: "10.1007/978-3-030-67788-6_7",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_7",
    researchFocus: "the formal transformations that connect coded observations, accumulated unit networks, metric space, projection, and interpretable node placement in ENA",
    evidence: "The paper is a mathematical treatment of the method, specifying the objects and operations that underlie commonly used ENA outputs.",
    method: "It formalizes accumulation and matrix representations, describes how unit networks occupy a high-dimensional connection space, and explains projection and co-registration between network geometry and summary coordinates.",
    reportedPattern: "The derivation supports two core affordances: comparing the content of networks with summary statistics and interpreting those comparisons through network visualizations aligned with the model.",
    boundary: "Mathematical consistency does not guarantee construct validity, representative sampling, reliable coding, appropriate dependence assumptions, or a correct substantive interpretation.",
    contribution: "The formal account makes it possible to audit what each transformation preserves, removes, and displays instead of treating ENA as a plotting black box.",
    scene: "a transparent sequence from coded rows to matrices, high-dimensional vectors, and a co-registered network plot",
  },
  {
    id: 18,
    slug: "markov-chains-versus-ena-discourse",
    headline: "ENA and Markov chains offered complementary views of the same collaborative discourse",
    paperTitle: "Comparing the visual affordances of discrete time Markov chains and epistemic network analysis for analysing discourse connections",
    authors: ["Daniela Vasco", "Kate Thompson", "Sakinah Alhadad", "M. Zahid Juri"],
    venue: "Frontiers in Education",
    year: 2024,
    type: "journal",
    tags: ["method comparison", "Markov chains", "discourse connections", "collaborative learning", "visual affordances"],
    createdAt: "2026-08-02",
    doi: "10.3389/feduc.2024.1401996",
    publisherUrl: "https://www.frontiersin.org/articles/10.3389/feduc.2024.1401996/full",
    researchFocus: "what discrete-time Markov chains and ENA each make visible when applied to coded collaborative discourse",
    evidence: "Both methods were applied to one coded dataset from 15 high-school students working in computer, iPad, or interactive-whiteboard groups.",
    method: "The comparison holds the discourse evidence in common and examines how sequential transition modeling and co-occurrence network modeling represent connections at group level.",
    reportedPattern: "Both techniques supported analysis of frequent conceptual connections, but their different visual and analytic affordances licensed different kinds of conclusions about group dynamics.",
    boundary: "A small illustrative dataset cannot rank the methods universally, and apparent agreement between displays does not mean that transition probability and ENA connection weight estimate the same object.",
    contribution: "The paper encourages method choice based on the temporal question and estimand, and shows why complementary views can be more informative than a winner-take-all comparison.",
    scene: "one classroom discourse stream branching into a Markov transition view and an ENA co-occurrence view",
  },
  {
    id: 19,
    slug: "ena-temporal-trajectories",
    headline: "Trajectory visualization recovered temporal information hidden by aggregate ENA networks",
    paperTitle: "Trajectories in Epistemic Network Analysis",
    authors: ["Jais Brohinsky", "Cody Marquart", "Junting Wang", "A. R. Ruis", "David Williamson Shaffer"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["ENA trajectories", "temporal visualization", "aggregate networks", "process interpretation", "qualitative validation"],
    createdAt: "2026-08-03",
    doi: "10.1007/978-3-030-67788-6_8",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_8",
    researchFocus: "how successive partial networks can be represented as trajectories through an ENA space without discarding the aggregate model",
    evidence: "The authors compare aggregate and trajectory views on a previously studied temporal dataset whose qualitative interpretation is known.",
    method: "Accumulated network states are projected into a shared ENA space and connected in order, allowing direction, path, and timing to be inspected alongside endpoint and aggregate patterns.",
    reportedPattern: "The trajectory view represented temporal information that the aggregate display omitted and produced patterns consistent with the established qualitative account.",
    boundary: "The paper introduces visualization and interpretation rather than a complete inferential framework for testing arbitrary path differences in trajectory space.",
    contribution: "It gives analysts a principled way to ask not only where networks differ, but how modeled connections developed across an ordered activity.",
    scene: "ordered network states forming two interpretable paths through one shared epistemic space",
  },
  {
    id: 20,
    slug: "future-stem-selves-identity",
    headline: "ENA contrasted how students and alumni connected possible future STEM selves",
    paperTitle: "Possible future selves in STEM: an epistemic network analysis of identity exploration in minoritized students and alumni",
    authors: ["Yiyun Kate Fan", "Amanda Barany", "Aroutis Foster"],
    venue: "International Journal of STEM Education",
    year: 2023,
    type: "journal",
    tags: ["STEM identity", "possible future selves", "minoritized learners", "alumni comparison", "interview discourse"],
    createdAt: "2026-08-04",
    doi: "10.1186/s40594-023-00412-z",
    publisherUrl: "https://stemeducationjournal.springeropen.com/articles/10.1186/s40594-023-00412-z",
    researchFocus: "how current students and alumni in a STEM minority participation program connected identity themes while imagining future roles",
    evidence: "Interview discourse from present and past program participants was coded for identity themes, modeled as group networks, and interpreted again through qualitative excerpts.",
    method: "ENA compared the organization of identity exploration across career stages, while the qualitative return supplied context for why particular themes connected.",
    reportedPattern: "Students connected action-taking with less-certain possible STEM roles, whereas alumni integrated a broader and more holistic set of identity facets when describing their futures.",
    boundary: "The cross-sectional student–alumni comparison, small program-linked samples, and interview design cannot establish individual developmental change or a causal program effect.",
    contribution: "The study models identity exploration as a configuration of themes while preserving participant discourse as the interpretive anchor.",
    scene: "current students and alumni mapping different but connected pathways toward possible STEM futures",
  },
  {
    id: 21,
    slug: "directed-epistemic-network-analysis",
    headline: "Directed ENA retained order that standard co-occurrence networks could miss",
    paperTitle: "Directed Epistemic Network Analysis",
    authors: ["Ariel Fogel", "Zachari Swiecki", "Cody Marquart", "Zhiqiang Cai", "Yeyu Wang", "Jais Brohinsky", "Amanda Siebert-Evenstone", "Brendan Eagan", "A. R. Ruis", "David Williamson Shaffer"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["directed ENA", "event order", "weighted networks", "team communication", "method extension"],
    createdAt: "2026-08-05",
    doi: "10.1007/978-3-030-67788-6_9",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_9",
    researchFocus: "how ENA can account for both interdependence and the order in which coded events occur",
    evidence: "The method is demonstrated with communications from two United States Navy commanders whose qualitative patterns were already distinguishable.",
    method: "Directed edges preserve source-to-target order within the modeled context, extending the usual undirected co-occurrence representation while retaining weighted network comparison.",
    reportedPattern: "Standard ENA did not represent the qualitative distinction in the demonstration as clearly, while the directed model captured the ordered difference between commanders.",
    boundary: "A two-case demonstration establishes methodological possibility, not general superiority; direction is meaningful only when ordering, windows, and event semantics support it.",
    contribution: "The extension helps researchers distinguish questions about association from questions in which the direction of activity is part of the phenomenon.",
    scene: "two command teams with contrasting directional communication flows represented as arrowed epistemic networks",
  },
  {
    id: 22,
    slug: "reproducible-open-coding-kit-ena",
    headline: "An open coding workflow connected qualitative transparency with reproducible ENA",
    paperTitle: "Using the Reproducible Open Coding Kit & Epistemic Network Analysis to model qualitative data",
    authors: ["Szilvia Zörgő", "Gjalt-Jorn Peters"],
    venue: "Health Psychology and Behavioral Medicine",
    year: 2022,
    type: "journal",
    tags: ["reproducible open coding", "qualitative workflow", "open science", "ENA pipeline", "health research"],
    createdAt: "2026-08-06",
    doi: "10.1080/21642850.2022.2119144",
    publisherUrl: "https://www.tandfonline.com/doi/full/10.1080/21642850.2022.2119144",
    researchFocus: "how an open, documented coding environment can connect qualitative data preparation with a reproducible ENA model",
    evidence: "The article presents the Reproducible Open Coding Kit as a workflow for preserving source material, code definitions, coded segments, and analytic decisions before network modeling.",
    method: "Structured project files and inspectable transformations make it possible to move from qualitative evidence to ENA while retaining provenance and reusable artifacts.",
    reportedPattern: "The worked workflow demonstrates that reproducibility can include the coding and interpretation chain rather than beginning only after a numeric matrix exists.",
    boundary: "Open tools and saved files do not automatically make codes valid, protect sensitive participants, eliminate researcher judgment, or guarantee that another team will reach the same interpretation.",
    contribution: "It provides a practical architecture for auditability at the junction where many mixed-methods analyses otherwise lose their qualitative provenance.",
    scene: "an open research workspace linking transcripts, code definitions, coded segments, and a reproducible ENA output",
  },
  {
    id: 23,
    slug: "parsimonious-ena-code-removal",
    headline: "Parsimonious code removal sought simpler ENA models without losing interpretive alignment",
    paperTitle: "Simplification of Epistemic Networks Using Parsimonious Removal with Interpretive Alignment",
    authors: ["Yeyu Wang", "Zachari Swiecki", "A. R. Ruis", "David Williamson Shaffer"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["model parsimony", "code removal", "interpretive alignment", "model refinement", "sensitivity analysis"],
    createdAt: "2026-08-07",
    doi: "10.1007/978-3-030-67788-6_10",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_10",
    researchFocus: "how analysts can identify smaller ENA code sets while protecting both explanatory performance and the alignment between quantitative features and qualitative meaning",
    evidence: "The proposed procedure was applied to a well-studied dataset with an existing published and validated eight-code ENA model.",
    method: "Parsimonious Removal with Interpretive Alignment systematically evaluates combinations of removed codes and compares candidate reduced models with the established model.",
    reportedPattern: "The demonstration identified reduced models likely to retain explanatory power and interpretive alignment, showing that simplification can be evaluated rather than improvised.",
    boundary: "Success against one established model does not justify deleting codes solely for visual neatness or guarantee that the same criterion preserves meaning in another study.",
    contribution: "The paper turns parsimony into a joint statistical and interpretive audit instead of treating fewer nodes as automatically better.",
    scene: "an eight-code epistemic network being carefully simplified while qualitative meanings remain visibly tethered",
  },
  {
    id: 24,
    slug: "subject-specific-teacher-professional-vision",
    headline: "Biology and mathematics experts connected classroom-management noticing differently",
    paperTitle: "The subject matters for the professional vision of classroom management: an exploratory study with biology and mathematics expert teachers",
    authors: ["Rebekka Stahnke", "Marita Friesen"],
    venue: "Frontiers in Education",
    year: 2023,
    type: "journal",
    tags: ["teacher professional vision", "classroom management", "subject specificity", "eye tracking", "think-aloud data"],
    createdAt: "2026-08-08",
    doi: "10.3389/feduc.2023.1253459",
    publisherUrl: "https://www.frontiersin.org/articles/10.3389/feduc.2023.1253459/full",
    researchFocus: "whether expert biology and mathematics teachers differ in how they notice and reason about classroom-management events",
    evidence: "Twenty secondary-school expert teachers viewed video clips while eye movements and retrospective think-aloud explanations were recorded.",
    method: "The researchers combined visual-attention evidence with quantitative content analysis and ENA of the knowledge-based reasoning expressed in think-aloud data.",
    reportedPattern: "Biology experts more often connected planning-oriented alternatives such as structure and room preparation, whereas mathematics experts were more evaluative and focused on behaviour management and immediate engagement.",
    boundary: "The small exploratory sample, selected video settings, retrospective verbalization, and subject grouping do not establish fixed traits of all biology or mathematics teachers.",
    contribution: "The mixed evidence shows how professional vision can be analyzed as subject-linked configurations of noticing and reasoning rather than a single expertise score.",
    scene: "biology and mathematics teachers viewing the same classroom video while distinct reasoning networks emerge",
  },
  {
    id: 25,
    slug: "curriculum-design-stem-identity",
    headline: "A museum course linked weekly design choices with middle-school STEM identity exploration",
    paperTitle: "Connecting Curricular Design and Student Identity Change: An Epistemic Network Analysis",
    authors: ["Amanda Barany", "Mamta Shah", "Aroutis Foster"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["curriculum design", "STEM identity", "projective reflection", "museum learning", "middle school"],
    createdAt: "2026-08-10",
    doi: "10.1007/978-3-030-67788-6_11",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_11",
    researchFocus: "how intentionally designed activities supported different processes of environmental-science identity exploration",
    evidence: "The paper examines session three of the play-based Virtual City Planning course with 18 middle-school learners at a local science museum.",
    method: "Projective Reflection guided curriculum design and assessment; ENA visualized connections among identity facets across weeks, and qualitative examination of student reflections contextualized the networks.",
    reportedPattern: "The results linked the design of weekly activities with the identity facets students emphasized, illustrating shifting processes of identity exploration.",
    boundary: "A small design-based case without a randomized counterfactual cannot isolate curricular components or establish durable identity change and later career acquisition.",
    contribution: "The study shows how curriculum, reflection, and network evidence can be coordinated to refine identity-supporting learning environments.",
    scene: "middle-school learners planning an environmentally resilient virtual city as future-science identity connections develop",
  },
  {
    id: 26,
    slug: "children-writing-cognitive-networks",
    headline: "Six years of writing revealed subject-, grade-, and gender-linked cognitive network patterns",
    paperTitle: "A thematic-cognitive perspective for exploring the writing skills of children: a textual analysis using ENA",
    authors: ["Jianheng Zhang", "Tiong-Thye Goh", "Dexin Chen", "Yuan Gong", "Bing Yang", "Liqin Pan", "Ting Song", "Shiqi Yu", "Hanzhen Li"],
    venue: "Frontiers in Psychology",
    year: 2025,
    type: "journal",
    tags: ["children writing", "cognitive networks", "grade development", "textual analysis", "personalized instruction"],
    createdAt: "2026-08-11",
    doi: "10.3389/fpsyg.2025.1494111",
    publisherUrl: "https://www.frontiersin.org/articles/10.3389/fpsyg.2025.1494111/full",
    researchFocus: "how thematic and cognitive structures in children's writing vary across subjects, grades, and gender groups",
    evidence: "The researchers encoded six years of primary-school writing and constructed network maps to inspect developmental and group-linked patterns.",
    method: "ENA represented connections among coded thematic and cognitive elements so that writing development could be examined as organization rather than only vocabulary or score differences.",
    reportedPattern: "The analysis reported distinct and nuanced network configurations across subjects, grade levels, and gender groups.",
    boundary: "Observed group patterns do not define individual ability, prove developmental causes, or justify essentialist gender conclusions; validity also depends on the coding scheme and corpus composition.",
    contribution: "The study offers a relational lens for generating instruction hypotheses while requiring teachers to return from group maps to actual student texts.",
    scene: "children's writing pages across six grade levels transforming into layered thematic and cognitive networks",
  },
  {
    id: 27,
    slug: "self-regulated-learning-bettys-brain",
    headline: "Log-trace networks compared self-regulation among higher- and lower-performing learners",
    paperTitle: "Using Epistemic Networks to Analyze Self-regulated Learning in an Open-Ended Problem-Solving Environment",
    authors: ["Luc Paquette", "Theodore Grant", "Yingbin Zhang", "Gautam Biswas", "Ryan Baker"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["self-regulated learning", "Betty's Brain", "log traces", "open-ended problem solving", "performance groups"],
    createdAt: "2026-08-13",
    doi: "10.1007/978-3-030-67788-6_13",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_13",
    researchFocus: "how self-regulated learning actions co-occur within and across phases of open-ended problem solving",
    evidence: "Log traces came from learners using Betty's Brain, where actions involved information seeking, solution construction, and solution assessment.",
    method: "The authors coded trace actions into the three problem-solving categories and used ENA to compare relational configurations for lower- and higher-performing groups.",
    reportedPattern: "The group networks provided an overall view of how action types combined, revealing self-regulatory organization that isolated event frequencies would not show.",
    boundary: "Performance-group differences in observational trace data do not demonstrate that a particular action connection caused achievement or that every logged click represents the intended cognitive process.",
    contribution: "The work demonstrates a reproducible path from ordered interaction logs to interpretable hypotheses about regulation in open-ended environments.",
    scene: "learners navigating an open-ended science environment as information seeking, construction, and assessment actions connect",
  },
  {
    id: 28,
    slug: "desktop-vr-collaborative-sensemaking",
    headline: "Desktop and VR teams emphasized different parts of collaborative mind-map work",
    paperTitle: "Desktop versus VR for collaborative sensemaking",
    authors: ["Ying Yang", "Tim Dwyer", "Zachari Swiecki", "Benjamin Lee", "Michael Wybrow", "Maxime Cordeil", "Teresa Wulandari", "Bruce H. Thomas", "Mark Billinghurst"],
    venue: "Frontiers in Virtual Reality",
    year: 2025,
    type: "journal",
    tags: ["virtual reality", "collaborative sensemaking", "mind mapping", "embodied interaction", "desktop comparison"],
    createdAt: "2026-08-14",
    doi: "10.3389/frvir.2025.1570383",
    publisherUrl: "https://www.frontiersin.org/articles/10.3389/frvir.2025.1570383/full",
    researchFocus: "whether desktop and immersive virtual-reality workspaces support different patterns of information sharing and collaborative sensemaking",
    evidence: "Groups of four participants, each holding exclusive starting information, completed sensemaking tasks with purpose-built desktop and VR mind-mapping systems.",
    method: "The study combined relational analysis of mind-mapping activity with post hoc analysis, observation, and participant feedback to compare the two interfaces.",
    reportedPattern: "VR activity focused more on problem solving, whereas desktop activity focused more on organizing the mind map; the authors connect this contrast to embodied and interface affordances.",
    boundary: "System-specific tasks and post hoc interpretation do not prove an inherent advantage of either medium, and interface maturity may be entangled with immersion.",
    contribution: "The result converts a broad desktop-versus-VR question into specific design needs, including better authoring and automatic organization support in immersive tools.",
    scene: "a four-person team building the same mind map in desktop and immersive VR workspaces with different activity networks",
  },
  {
    id: 29,
    slug: "single-case-lifelong-learning-analytics",
    headline: "Single-case ENA made one learner's long-term activity patterns open to contextual inspection",
    paperTitle: "The Value of Epistemic Network Analysis in Single-Case Learning Analytics: A Case Study in Lifelong Learning",
    authors: ["Luis P. Prieto", "María Jesús Rodríguez-Triana", "Tobias Ley", "Brendan Eagan"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["single-case analytics", "lifelong learning", "idiographic analysis", "multimodal evidence", "case interpretation"],
    createdAt: "2026-08-15",
    doi: "10.1007/978-3-030-67788-6_14",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_14",
    researchFocus: "what ENA contributes when learning analytics centers on one person's activity across a lifelong-learning case",
    evidence: "The paper uses a single case to connect temporally organized learning activity with contextual qualitative evidence rather than treating a group average as the only valid analytic target.",
    method: "ENA is used as an idiographic comparison and visualization tool, organizing coded relations within the case so that changing configurations can be examined against the learner's context.",
    reportedPattern: "The case illustrates how network views can surface internally meaningful contrasts and guide a return to episodes that would be obscured by population aggregation.",
    boundary: "One case cannot estimate population prevalence or general treatment effects, and apparent within-person change remains sensitive to coding, time boundaries, and the selected comparison periods.",
    contribution: "The paper expands the learning-analytics repertoire for intensive cases while making contextual interpretation and modest generalization explicit requirements.",
    scene: "one lifelong learner's episodes arranged as an auditable timeline of changing epistemic networks",
  },
  {
    id: 30,
    slug: "mooc-learning-sentiment-networks",
    headline: "MOOC sentiment networks varied with performance groups and discussion topics",
    paperTitle: "Analyzing Learning Sentiments on a MOOC Discussion Forum Through Epistemic Network Analysis",
    authors: ["Jianhui Yu"],
    venue: "The International Review of Research in Open and Distributed Learning",
    year: 2025,
    type: "journal",
    tags: ["MOOC discussion", "learning sentiment", "performance level", "topic differences", "online learning"],
    createdAt: "2026-08-16",
    doi: "10.19173/irrodl.v26i1.7965",
    publisherUrl: "https://www.irrodl.org/index.php/irrodl/article/view/7965",
    researchFocus: "how connections among expressed learning sentiments differ by MOOC performance level and discussion topic",
    evidence: "The corpus contained discussion posts from 158 MOOC participants, grouped for comparisons of sentiment patterns and topic-linked engagement.",
    method: "Coded sentiments and learning topics were modeled with ENA so the analysis could compare which emotional states and engagement categories tended to connect.",
    reportedPattern: "Higher-score participants showed stronger engagement–neutral and neutral–frustration connections, fewer frustration links with delight or boredom, and engagement connected broadly across topics; the lower-score group showed a narrower engagement–experience link.",
    boundary: "Forum expression is not a complete measure of emotion, and performance-group associations cannot establish that a sentiment pattern caused achievement or will transfer across MOOCs.",
    contribution: "The study offers instructors relational signals for forming targeted support hypotheses while preserving the need for validation and learner context.",
    scene: "MOOC discussion posts forming contrasting sentiment networks for higher- and lower-score learner groups",
  },
  {
    id: 31,
    slug: "gameplay-change-event-networks",
    headline: "Repeated game sessions revealed shifts between short-term and self-sustaining strategies",
    paperTitle: "Counting the Game: Visualizing Changes in Play by Incorporating Game Events",
    authors: ["Jennifer Scianna", "David Gagnon", "Mariah A. Knowles"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["game learning analytics", "systems thinking", "event logs", "repeated play", "strategy change"],
    createdAt: "2026-08-17",
    doi: "10.1007/978-3-030-67788-6_15",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_15",
    researchFocus: "how incorporating game events into ENA can visualize changes in complex-systems play across repeated sessions",
    evidence: "Anonymous logs from the educational game Lakeland were sampled for secondary science players who returned for more than one session during classroom use.",
    method: "The authors compared networks from the same player across games, linking event patterns to time manipulation and short-term versus self-sustaining strategies in a phosphorus-cycle simulation.",
    reportedPattern: "Repeated play showed significant differences in responses to game events and patterns consistent with greater attention to temporally distant phenomena and sustainable strategies.",
    boundary: "Selected repeat players and in-game traces do not independently establish durable systems understanding, and logged strategies require interpretation within the game's mechanics.",
    contribution: "The paper shows how event-aware networks can make behavioral change visible without reducing gameplay to a final score.",
    scene: "a learner revisiting an ecological systems game as event logs shift from short-term fixes toward sustainable strategies",
  },
  {
    id: 32,
    slug: "knowledge-building-shared-agency",
    headline: "Online and face-to-face Knowledge Building talk showed different shared-agency patterns",
    paperTitle: "Investigating shared agency in student Knowledge Building discourse using epistemic network analysis",
    authors: ["Aloysius Ong", "Chew-Lee Teo", "Alwyn-Vwen-Yen Lee", "Guangji Yuan"],
    venue: "Research and Practice in Technology Enhanced Learning",
    year: 2025,
    type: "journal",
    tags: ["shared epistemic agency", "Knowledge Building", "synchronous discourse", "Grade 5", "hybrid collaboration"],
    createdAt: "2026-08-18",
    doi: "10.58459/rptel.2026.21006",
    publisherUrl: "https://rptel.apsce.net/index.php/RPTEL/article/view/2026-21006",
    researchFocus: "how shared epistemic agency appears in online and face-to-face student discourse during Knowledge Building",
    evidence: "A Grade 5 class completed a 2.5-hour social-studies lesson with synchronous Knowledge Forum activity and small-group oral discussion.",
    method: "Forum notes and talk transcripts were coded for semantic contribution types, then ENA compared weighted connections and group engagement configurations across modalities.",
    reportedPattern: "Online and oral discussions showed distinct connection patterns and degrees of idea development, with additional variation in how individual groups engaged.",
    boundary: "One class and one lesson provide a situated process account, not a universal ranking of discussion modalities or proof that a platform caused shared agency.",
    contribution: "The study makes modality and group variation visible while retaining discourse as evidence for interpreting collaborative agency.",
    scene: "Grade 5 students moving between Knowledge Forum and table talk as different idea-development networks emerge",
  },
  {
    id: 33,
    slug: "preschool-curiosity-trajectories",
    headline: "A ten-month mother–child case traced how scientific curiosity changed over time",
    paperTitle: "What Would Happen if Humans Disappeared from Earth? Tracing and Visualizing Change in a Pre-School Child’s Domain-Related Curiosities",
    authors: ["Mamta Shah", "Amanda Barany", "Amanda Siebert-Evenstone"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["preschool curiosity", "parent-child interaction", "self-ethnography", "longitudinal case", "science questioning"],
    createdAt: "2026-08-19",
    doi: "10.1007/978-3-030-67788-6_16",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_16",
    researchFocus: "how sustained family engagement can reveal changing domain-related scientific curiosity in early childhood",
    evidence: "The self- and quantitative-ethnographic case follows one mother–son dyad across ten months of naturally occurring scientific questions and interactions.",
    method: "Coded episodes are organized relationally and temporally so changes in the child's curiosity can be visualized while the family context remains available for close interpretation.",
    reportedPattern: "The case documents evolving connections in scientific questioning and illustrates mechanisms through which deep curiosity may be sustained over a longer period.",
    boundary: "A self-ethnographic dyad offers depth but cannot estimate typical preschool development, separate parent influence from maturation, or support broad causal generalization.",
    contribution: "The study demonstrates how longitudinal QE can preserve the texture of one developing curiosity while making change systematically inspectable.",
    scene: "a preschool child and parent exploring an Earth-without-humans question across a ten-month curiosity timeline",
  },
  {
    id: 34,
    slug: "older-adults-ai-learning-drawings",
    headline: "Drawings and interviews mapped how older adults imagined AI-supported learning",
    paperTitle: "Older adults’ conceptions of AI-supported learning: an epistemic network analysis based on AI-generated drawings",
    authors: ["Shu Zhao", "Congxin Wu", "Ziqi Wang", "Meizhao Guo", "Xian Zhao"],
    venue: "Smart Learning Environments",
    year: 2026,
    type: "journal",
    tags: ["older adult learning", "AI-generated drawings", "technology acceptance", "visual elicitation", "lifelong learning"],
    createdAt: "2026-08-20",
    doi: "10.1186/s40561-026-00443-3",
    publisherUrl: "https://link.springer.com/article/10.1186/s40561-026-00443-3",
    researchFocus: "how older adults with different backgrounds conceptualize and respond to AI-supported learning",
    evidence: "Seventy-five older adults produced hand-drawn and AI-generated images, coded into six categories and 20 elements, and interviews supplied supplementary interpretation.",
    method: "Drawing-based ENA compared how visual elements connected across image types and participant characteristics, while interview evidence helped interpret acceptance and assistance needs.",
    reportedPattern: "Hand drawings reflected life-based understandings, AI images were more structured, background characteristics related to content and style, and most participants described the tools as practical and were willing to use them.",
    boundary: "Prompting, tool design, coding choices, novelty, and a situated sample limit claims about all older adults or long-term adoption; demographic contrasts must not be treated as fixed deficits.",
    contribution: "The mixed visual and interview design surfaces contextual requirements for inclusive AI learning rather than assuming that one interface fits every older learner.",
    scene: "older adults comparing hand-drawn and AI-assisted visions of learning while supportive design needs connect around them",
  },
  {
    id: 35,
    slug: "social-presence-mooc-network-position",
    headline: "Automated social-presence coding was linked with learners' positions in a MOOC network",
    paperTitle: "Does Social Presence Play a Role in Learners’ Positions in MOOC Learner Network? A Machine Learning Approach to Analyze Social Presence in Discussion Forums",
    authors: ["Wenting Zou", "Zilong Pan", "Chenglu Li", "Min Liu"],
    venue: "2nd International Conference on Quantitative Ethnography (ICQE 2020)",
    year: 2021,
    type: "conference",
    tags: ["social presence", "MOOC network position", "automated content analysis", "discussion forums", "peer interaction"],
    createdAt: "2026-08-21",
    doi: "10.1007/978-3-030-67788-6_17",
    publisherUrl: "https://link.springer.com/chapter/10.1007/978-3-030-67788-6_17",
    researchFocus: "whether categories of social presence in discussion posts are associated with learners' structural positions in a MOOC interaction network",
    evidence: "The authors built and tested a machine-learning classifier for student posts, then measured learner position using in-degree, closeness, and betweenness centrality.",
    method: "Automated content categories were linked with social-network measures, and learners were grouped by network position to compare the social presence represented in their posts.",
    reportedPattern: "Certain forms of social presence correlated positively with network measures, and position groups differed in the social-presence patterns they displayed.",
    boundary: "Correlations between classified language and network position do not show that strategic posting causes engagement, and both classifier error and platform participation shape the observed relations.",
    contribution: "The study integrates textual and relational analytics while showing the validation and causal boundaries required before turning a pattern into learner advice.",
    scene: "MOOC discussion participants whose differently coded social-presence posts connect to distinct network positions",
  },
];

function buildFullSummary(spec: BackfillNewsSpec) {
  const publicationKind = spec.type === "journal" ? "journal article" : "conference paper";
  return `${spec.paperTitle}, a ${spec.year} ${publicationKind} by ${spec.authors.join(", ")}, examines ${spec.researchFocus}. ${spec.evidence} The review therefore starts from the paper's actual evidence source and purpose rather than from the visual appeal of its final network.

The analytic move is important because ENA represents relations among coded elements, not merely how often each element appears. ${spec.method} In a defensible workflow, units define whose or what network is accumulated, conversation boundaries and windows define where proximity can become a connection, and the coding scheme defines which aspects of the source material enter the model. Those decisions determine the estimand before normalization, projection, rotation, or plotting begins. A network line is consequently a modeled connection under a documented specification; it is not a direct photograph of thought, collaboration, identity, or learning.

The authors report that ${spec.reportedPattern.charAt(0).toLowerCase()}${spec.reportedPattern.slice(1)} This result is most useful as a relational account: it identifies which coded elements were organized together under the study's data and model choices. It should be read alongside unit-level variation, source excerpts or events, and any reported comparison statistics. Visual distance, line thickness, or an attractive subtraction network alone cannot establish practical importance. When a paper combines network output with qualitative return, experimental contrast, trace evidence, or another analytic view, those components strengthen interpretation because they make competing explanations easier to inspect.

The claim boundary is equally central. ${spec.boundary} ENA cannot on its own repair a weak sample, an unstable codebook, missing contextual evidence, inappropriate dependence assumptions, or a window that crosses contexts that should remain separate. Nor does dimensional reduction preserve every feature of a high-dimensional connection space. The safest conclusion separates three layers: what was observed or collected, what the specified model represents, and what broader explanation the research design can support. Any transfer to a new population, language, activity, platform, or analytic pipeline requires fresh validation rather than visual analogy.

For ENA.HK readers, the paper's durable contribution is that ${spec.contribution.charAt(0).toLowerCase()}${spec.contribution.slice(1)} A reproducible application should save the source-data provenance, segmentation and ordering rules, unit and conversation fields, code definitions, window and weighting choices, normalization and rotation settings, software version, exclusions, and sensitivity checks. It should also retain a route back from every interpreted edge to the qualitative excerpt, observed event, trace record, image element, or document that generated it. That evidence chain keeps the quantitative model and ethnographic meaning in deliberate contact while preventing a descriptive network pattern from being overstated as a causal or universal finding.`;
}

function buildArticle(spec: BackfillNewsSpec): NewsArticle {
  const id = `ena-${String(spec.id).padStart(3, "0")}`;
  const mediaStem = `${id}-${spec.slug}`;
  const shortSummary = `${spec.researchFocus.charAt(0).toUpperCase()}${spec.researchFocus.slice(1)}. ${spec.reportedPattern} ${spec.boundary}`;

  return {
    id,
    slug: spec.slug,
    title: spec.headline,
    authors: spec.authors,
    venue: spec.venue,
    year: spec.year,
    type: spec.type,
    tags: spec.tags,
    image: `/images/research/covers/${mediaStem}.png`,
    imageAlt: `Photorealistic editorial photograph of ${spec.scene}`,
    summaryImage: `/images/research/summary/${mediaStem}-summary.png`,
    summaryImageAlt: `Photorealistic editorial photograph of ${spec.scene}`,
    summaryAudio: `/audio/research/${mediaStem}-summary.m4a`,
    summaryAudioTitle: `Listen to the reviewed ${spec.type === "journal" ? "journal-article" : "conference-paper"} summary`,
    shortSummary,
    fullSummary: buildFullSummary(spec),
    keyTakeaways: [spec.method, spec.reportedPattern, spec.boundary],
    whyItMatters: `${spec.contribution} For practice, it also provides a concrete checkpoint for keeping modeled connections tied to inspectable evidence and appropriately bounded claims.`,
    sourceUrl: `https://doi.org/${spec.doi}`,
    sourceUrls: [
      { label: "Canonical DOI record", url: `https://doi.org/${spec.doi}` },
      { label: "Publisher or repository record", url: spec.publisherUrl },
    ],
    doi: spec.doi,
    createdAt: spec.createdAt,
  };
}

export const backfillNewsArticles: NewsArticle[] = backfillNewsSpecs.map(buildArticle);

export const backfillNewsImagePrompts = backfillNewsSpecs.map((spec) => ({
  id: `ena-${String(spec.id).padStart(3, "0")}`,
  slug: spec.slug,
  prompt: `Create a high-end photorealistic editorial photograph for an ENA research review: ${spec.scene}. Landscape 16:10 composition, real people with natural faces, skin texture, hands, clothing, practical lighting, and camera depth of field; use subtle translucent node-and-edge overlays only when they clarify the research setting. No anime, no cartoon, no illustration, no painterly treatment, no vector art, no 3D-rendered people, no plastic skin, no readable text, no letters, no numbers, no logos, no watermark.`,
}));
