import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import JsonLd from "@/components/JsonLd";
import { isLocale, type Locale } from "@/lib/i18n";
import { getPluginLabCopy, pluginAuthorRoleLabel, pluginContentForLocale, pluginContributionLabel, pluginLifecycleLabel, pluginPermissionValueLabel, pluginReviewStatusLabel, pluginScientificEvidenceLabel } from "@/lib/plugin-lab/i18n";
import { getOpenEnaPluginBySlug, OPEN_ENA_PLUGIN_CATALOG } from "@/lib/open-ena/plugins/catalog";
import { pageMetadata } from "@/lib/metadata";
import { pluginSoftwareApplicationJsonLd } from "@/lib/structured-data";

export function generateStaticParams() { return OPEN_ENA_PLUGIN_CATALOG.map((plugin) => ({ slug: plugin.slug })); }

export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> {
  const { locale, slug } = await params; const typed = isLocale(locale) ? locale : "en"; const plugin = getOpenEnaPluginBySlug(slug); if (!plugin) return {};
  const localized = pluginContentForLocale(plugin, typed); return pageMetadata({ locale: typed, path: `/plugins/${plugin.slug}`, title: localized.content.name, description: localized.content.tagline });
}

export default async function PluginDetailPage({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const { locale, slug } = await params; if (!isLocale(locale)) notFound(); const plugin = getOpenEnaPluginBySlug(slug); if (!plugin) notFound();
  const typed = locale as Locale; const copy = getPluginLabCopy(typed); const localized = pluginContentForLocale(plugin, typed);
  const structuredData = pluginSoftwareApplicationJsonLd({ plugin, locale: typed, name: localized.content.name, description: localized.content.tagline });
  return <article className="container plugin-detail" lang={localized.fallback ? "en" : undefined}>
    <JsonLd data={structuredData} />
    {localized.fallback ? <p className="plugin-language-note">{localized.fallbackNotice}</p> : null}
    <header><div className="plugin-card-meta">{plugin.contributionKinds.map((kind) => <span key={kind}>{pluginContributionLabel(kind, typed)}</span>)}<span>{pluginLifecycleLabel(plugin.lifecycle, typed)}</span></div><h1>{localized.content.name}</h1><p className="plugin-detail-lede">{localized.content.tagline}</p><div className="plugin-analysis-answer" data-answer={plugin.changesAnalysis ? "yes" : "no"}><span>{copy.changesAnalysis}</span><strong>{plugin.changesAnalysis ? copy.yes : copy.no}</strong></div><div className="button-row"><Link className="button button-primary" href={`/${typed}/open-ena`}>{copy.tryPlugin}</Link><Link className="button button-secondary" href={`/${typed}/plugins/propose`}>{copy.propose}</Link></div></header>
    <section><h2>{copy.researchQuestion}</h2><p>{localized.content.researchQuestion}</p></section>
    <div className="plugin-status-grid"><section><h2>{copy.productStatus}</h2><p>{pluginLifecycleLabel(plugin.lifecycle, typed)}</p></section><section><h2>{copy.scientificEvidence}</h2><p>{pluginScientificEvidenceLabel(plugin.scientificEvidence, typed)}</p></section><section><h2>{copy.engineeringAssurance}</h2><ul><li>{copy.automatedTests}: {pluginReviewStatusLabel(plugin.engineeringAssurance.automatedTests, typed)}</li><li>{copy.browserRuntime}: {pluginReviewStatusLabel(plugin.engineeringAssurance.browserRuntime, typed)}</li><li>{copy.securityPrivacy}: {pluginReviewStatusLabel(plugin.engineeringAssurance.securityPrivacyReview, typed)}</li><li>{copy.lastReviewed}: {plugin.engineeringAssurance.lastReviewed}</li></ul></section></div>
    <div className="plugin-detail-grid"><section><h2>{copy.claims}</h2><ul>{localized.content.claims.map((claim) => <li key={claim}>{claim}</li>)}</ul></section><section><h2>{copy.nonClaims}</h2><ul>{localized.content.nonClaims.map((claim) => <li key={claim}>{claim}</li>)}</ul></section><section><h2>{copy.limitations}</h2><ul>{localized.content.limitations.map((limitation) => <li key={limitation}>{limitation}</li>)}</ul></section><section><h2>{copy.compatibility}</h2><p>Open ENA Core API {plugin.compatibility.coreApi}; jENA {plugin.compatibility.jenaVersions.join(", ")}; {plugin.compatibility.analysisKinds.join(", ")}; {plugin.compatibility.modelTypes.join(", ")}; ≥ {plugin.compatibility.minimumDimensions} {copy.dimensions}.</p></section><section><h2>{copy.permissions}</h2><p>{plugin.permissions.dataAccessTier}; {copy.network}: {pluginPermissionValueLabel(plugin.permissions.network, typed)}; {copy.storage}: {pluginPermissionValueLabel(plugin.permissions.storage, typed)}; {copy.externalProcessing}: {plugin.permissions.externalProcessing ? copy.yes : copy.no}.</p></section><section><h2>{copy.license}</h2><p>{copy.codeLicense}: {plugin.licenses.code}; {copy.documentationLicense}: {plugin.licenses.documentation}; {copy.sampleDataLicense}: {plugin.licenses.sampleData}.</p></section><section><h2>{copy.team}</h2><ul>{plugin.authors.map((author, index) => <li key={`${author.name}:${author.role}:${index}`}>{author.name}: {pluginAuthorRoleLabel(author.role, typed)}</li>)}</ul><p>{copy.maintainer}: {plugin.maintainer.name}</p></section><section><h2>{copy.source}</h2><p><a href={plugin.source.repository} target="_blank" rel="noreferrer">{copy.sourceRepository}</a></p><p>{copy.version}: <code>{plugin.version}</code></p><p><a href={plugin.citation}>{copy.citationRecord}</a></p></section><section><h2>{copy.provenanceBindings}</h2><dl><div><dt>{copy.sourceRevision}</dt><dd><code>{plugin.source.revision ?? copy.notYetBound}</code></dd></div><div><dt>{copy.artifactHash}</dt><dd><code>{plugin.source.artifactSha256 ?? copy.notYetBound}</code></dd></div><div><dt>{copy.fixtureHash}</dt><dd><code>{plugin.source.fixtureSetSha256 ?? copy.notYetBound}</code></dd></div><div><dt>{copy.methodSpecification}</dt><dd><code>{plugin.approvalBinding.methodSpecificationSha256 ?? copy.notYetBound}</code></dd></div><div><dt>{copy.reviewedManifest}</dt><dd><code>{plugin.approvalBinding.reviewedManifestSha256 ?? copy.notYetBound}</code></dd></div><div><dt>{copy.reviewReceipts}</dt><dd>{plugin.reviewReceipts.length}</dd></div></dl></section></div>
    <section className="plugin-changelog"><h2>{copy.changelog}</h2><ol>{plugin.changelog.map((change) => <li key={`${change.version}:${change.date}`}><strong><code>{change.version}</code> · <time dateTime={change.date}>{change.date}</time></strong><p>{change.summary[localized.language]}</p></li>)}</ol></section>
    <aside className="plugin-boundary-note"><strong>{copy.independentBoundaryTitle}</strong><p>{copy.independentBoundary}</p></aside>
  </article>;
}
